#ifndef __GAMEMAIN_H__
#define __GAMEMAIN_H__

//#define GAME_MENU_ITEM	4
//#define GAMEINFO_FRAME_THICKNESS	4
#define GAME_MENU_FORM_TITLE_HEIGHT 40	//Must >= 32
#define GAME_MENU_TITLE_GAP			12
//#define GAME_MENU_START_X				200
//#define GAME_MENU_START_Y				60
#define GAME_MENU_FORM_WIDTH			(WORD)250
#define GAME_MENU_ITEM_START_X		(_wMenuStartX+48)
#define GAME_MENU_ITEM_START_Y		(_wMenuStartY+GAME_MENU_FORM_TITLE_HEIGHT+GAME_MENU_TITLE_GAP)//(WORD)GAME_MENU_START_Y+GAME_MENU_FORM_TITLE_HEIGHT+GAME_MENU_TITLE_GAP
#define GAME_MENU_ITEM_HEIGHT		30
#define GAME_MENU_ITEM_WIDTH		150
#define GAME_MENU_ITEM_GAP			GAME_MENU_TITLE_GAP
//#define GAME_MENU_FORM_HEIGHT		(WORD)(GAME_MENU_ITEM_HEIGHT+GAME_MENU_ITEM_GAP)*GAME_MENU_ITEM+(WORD)(GAME_MENU_FORM_TITLE_HEIGHT+GAME_MENU_TITLE_GAP)

#ifdef SHOW_MENU_ICON
#define OSDGAME_MENU_ENTRY_ITEMICON_BG_COLOR 119 //95+14
#define OSDGAME_MENU_ENTRY_TITLEICON_BG_COLOR 213 //95+118
#endif


typedef enum tagGAMEID
{
    GAME_NONE=0,
    GAME_MENU,
    GAME_TETRIS,
    GAME_GO5,
    GAME_SOKOBAN,
    GAME_RUSHHOUR,
    GAME_MINER,
}EN_GAME_ID;


typedef struct tagGAMEMENU_STRUCT{	
WORD *pwItemText;	
EN_GAME_ID gameID;
} GAMEMENU_STRUCT, *PGAMEMENU_STRUCT;

BYTE GAMEMAIN_ProcessKey(void);
void GAMEMAIN_Trigger(void);
void GAMEMAIN_ExitGame(void);
#endif //#ifndef __GAMEMAIN_H__
