//<---edit by program--------

    //Main->Language->OSD Sub menu,
    SETUP_LANGUAGE_OSD_BEGIN=35,
    SETUP_LANGUAGE_OSD_BASE=SETUP_LANGUAGE_OSD_BEGIN,
    SETUP_LANGUAGE_OSD_ENGLISH=SETUP_LANGUAGE_OSD_BASE,
    SETUP_LANGUAGE_OSD_SIMP_CHINESE,
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_SIMP_CHINESE,

//---edit by program-------->
