move jpegdec.c decoder\jpeg\.
move jpegfmt.c decoder\jpeg\.
move mpeg2dec.c decoder\mpeg\.
move mpeg2dec.h decoder\mpeg\.
move mpg_dram.c decoder\mpeg\.
move cdg.c decoder\.
move comdec.c decoder\.
move disp.c display\.
move subpict.c display\.
move cell.c navigate\.
move navigate.c navigate\.
move nvcmd.c navigate\.
move pgc.c navigate\.
move vcd20.c navigate\.
move cdinfo.c info\.
move dvdinfo.c info\.
move infofilter.c info\.
move udf.c info\.
move fat.c info\.
move parser.c parser\.
move par_int.c parser\.
move par_mpeg.c parser\.
move par_avi.c parser\.
move par_io.c parser\.
move lparser.h parser\.
move par_avi.h parser\.
move par_mpeg.h parser\.
move par_css.o parser\.
move par_css.h parser\.
move par_drm.h parser\.
move par_sptx.c parser\.
move par_mp4.c parser\.
move par_dvb.c parser\.
move par_dram.c parser\.
move par_dvb.h parser\.
move par_mp4.h parser\.
move usb.c usb\.
move jos_mem.o usb\.
move usbdi.o usb\.
move gamemain.c osdgame\.
move decore.c decoder\mp4\.
move mp4_dpart.c decoder\mp4\.
move mp4_header.c decoder\mp4\.
move mp4_header_311.c decoder\mp4\.
move move mp4_picture.c decoder\mp4\.
move mp4_picture_311.c decoder\mp4\.
move mp4_recon_gmc.c decoder\mp4\.
move mp4_tables.c decoder\mp4\.
move decore.h decoder\mp4\.
move getbits.h decoder\mp4\.
move mp4_dpart.h decoder\mp4\.
move mp4_header.h decoder\mp4\.
move mp4_tables.h decoder\mp4\.
move mp4_vars.h decoder\mp4\.
move tve.c tve\.
move card.c card\.
move msc.c card\.
move msc.h card\.
move sdc.c card\.
move sdc.h card\.
move xdc.c card\.
move xdc.h card\.
move nfc.c card\.
move nfc.h card\.
move nfchip.c card\.
move nfchip.h card\.
move fcmmgr.c card\.
move fcmmgr.h card\.