#include "winav.h"

#ifndef __OSD_H__
#include "osd.h"
#endif

#ifndef __SETUP_H__
#define __SETUP_H__


//////////////////////////////////////////////////////////////////////


// brian.171, high light all the setup area
// Define this would use VCD3.0 area as the background of entire Setup OSD area
#define SETUP_HIGHLIGHT_BACKGROUND

#ifdef SETUP_HIGHLIGHT_BACKGROUND
// Brian.171, define the setup VCD3.0 highlight color
#define SETUP_VCD30_COLOR       HAL_VCD30_COLOR_BLACK //We define a goup of values in hal.h. You can use them directly or define one for yourself.
                                                     //They are HAL_VCD30_COLOR_BLACK, HAL_VCD30_COLOR_BLUE, HAL_VCD30_COLOR_RED, HAL_VCD30_COLOR_WHITE, HAL_VCD30_COLOR_YELLOW, HAL_VCD30_COLOR_GREEN.
#define SETUP_VCD30_CONTRAST    0x7    //The range can be 0x1 to 0xf. The 0x1 is the lightest.

#else

#define SETUP_VCD30_COLOR       HAL_VCD30_COLOR_BLUE //We define a goup of values in hal.h. You can use them directly or define one for yourself.
                                                     //They are HAL_VCD30_COLOR_BLACK, HAL_VCD30_COLOR_BLUE, HAL_VCD30_COLOR_RED, HAL_VCD30_COLOR_WHITE, HAL_VCD30_COLOR_YELLOW, HAL_VCD30_COLOR_GREEN.
#define SETUP_VCD30_CONTRAST    0x7    //The range can be 0x1 to 0xf. The 0x1 is the lightest.
#endif

// Brian.171a
// This is a workaround to make SCF/SCB, FF look like paused (before the real KEY_PAUSE issue is solved)
// However add this would also make it change to PLAY mode when exit Setup.
#define PLAY_AFTER_EXIT_SETUP

// Brian.172r
//  define this to blink the selection bar
#define SETUP_BLINKING_SELECTION

// Brian2.78b
#define SUPPORT_BACK_DOOR_IN_RELEASE

// Brian0.87
//#define SUPPORT_EXTRA_PAL_MODE

// *** We have a more flexible way for this, so don't use the old method. *** Old method: // TCH1.01b; #define USE_DEFAULT_PASSWORD //If you don't want default password when reading the default value, please mark it.
// Brian1.24, flag for set default
#define USE_DEFAULT_PASSWORD 	            0x01
#define USE_DEFAULT_REGIONCODE 		    0x02
#define USE_DEFAULT_PARENTAL_CTRL	    0x04   // This is the Parental Control backdoor, not the Parental Level
#define USE_DEFAULT_APS_CTRL                0x08

#define SETUP_GLOBAL_OFFSET_X   0 
#define SETUP_GLOBAL_OFFSET_Y   0 

// Brian1.24, 
// READ_OPTIONAL_DEFAULT decides which one is set to default. 
// With our standard release, we still set parental, region code and APS to default.
// If you want to have differnt setting, just change the mask
// This is for BACKDOOR "1234"
#define READ_OPTIONAL_DEFAULT 	USE_DEFAULT_APS_CTRL|USE_DEFAULT_REGIONCODE|USE_DEFAULT_PARENTAL_CTRL
// This is for BACKDOOR "6666"
#define READ_TOTAL_DEFAULT              0xFF  // set all bit to 1 means set all to deafult value.

// This is for the Custom->Read (default)
#define SETUP_CUSTOM_READ_DEFAULT       USE_DEFAULT_APS_CTRL|USE_DEFAULT_REGIONCODE|USE_DEFAULT_PARENTAL_CTRL

#ifndef DOLBY_CERTIFICATION //kevin0.80
#define NO_DNR_ITEM //If you don't want the DNR item, please open this define
#endif

#define ENABLE_CUSTOM_SETUP //This define will enable all custom setup in VCD mode.
//#define SETUP_REDUCE_LUMINANCE //Open this define to reduce the luminance when entering SETUP menu.
//#define SETUP_NO_RGB_OUTPUT //Open this define to remove RGB value in video output, For 28AF, this has been defined in winav.h
//#define SETUP_NO_ANGLE_MARK   // Open this to remove the Angle menu, brian.161
//#define SETUP_NO_BRIGHTNESS_CONTRAST // Open this to remove the Brightness/Bontrast menu, brian.161


// User should modify here for Parental level
#define SETUP_DEFAULT_PARENTAL          SETUP_CUSTOM_PC_LEVEL_8
// User should modify here for ASPECT view
#ifdef  RELEASE_SETTING
#define SETUP_DEFAULT_ASPECT            SETUP_SCREEN_TV_TYPE_WIDE
#else
#define SETUP_DEFAULT_ASPECT            SETUP_SCREEN_TV_TYPE_LB
#endif      // RELEASE_SETTING

#define SETUP_DEFAULT_SCREEN_SAVER      SETUP_SCREEN_SAVER_ON  // Brian0.84 it is not implement yet
#define SETUP_DEFAULT_TV_SYSTEM         SETUP_SCREEN_TV_SYSTEM_NTSC
#define SETUP_DEFAULT_BRIGHTNESS        SETUP_SCREEN_BRIGHTNESS_NORMAL
#define SETUP_DEFAULT_CONTRAST          SETUP_SCREEN_CONTRAST_0
#define SETUP_DEFAULT_CHROM_PHASE	    SETUP_SCREEN_CHROM_PHASE_0 // Brian1.25, Chroma phase
#define SETUP_DEFAULT_VIDEO_OUTPUT      SETUP_SCREEN_VIDEO_OUTPUT_NORMAL
#define SETUP_DEFAULT_AUDIO_DIGITAL_OUT SETUP_AUDIO_DIGITAL_OUT_SPDIF_RAW
#ifdef SUPPORT_2_CHANNEL_ONLY // Brian1.06
#define SETUP_DEFAULT_AUDIO_ANALOG_OUT	SETUP_AUDIO_ANALOG_OUT_2CH // LLY2.82, 2CH
#else
#define SETUP_DEFAULT_AUDIO_ANALOG_OUT	SETUP_AUDIO_ANALOG_OUT_51CH 
#endif
#define SETUP_DEFAULT_AUDIO_DOWNMIX	SETUP_AUDIO_DOWNMIX_LORO 
#define SETUP_DEFAULT_AUDIO_PROLOGIC    SETUP_AUDIO_PROLOGIC_OFF // Brian1.08
#define SETUP_DEFAULT_AUDIO_CENTER      SETUP_AUDIO_CENTER_ON
#define SETUP_DEFAULT_AUDIO_REAR        SETUP_AUDIO_REAR_ON
#define SETUP_DEFAULT_AUDIO_SUBWOOFER   SETUP_AUDIO_SUBWOOFER_ON
#define SETUP_DEFAULT_AUDIO_LPCM        SETUP_AUDIO_LPCM_48K
#define SETUP_DEFAULT_AUDIO_DNR         SETUP_AUDIO_DNR_0
#define SETUP_DEFAULT_AUDIO_KARAOKE     SETUP_AUDIO_KARAOKE_ON

#define SETUP_DEFAULT_SMART_PLAY        SETUP_CUSTOM_SMART_PLAY_OFF

#ifdef    SETUP_NO_ANGLE_MARK
#define SETUP_DEFAULT_ANGLE_MARK        SETUP_CUSTOM_ANGLE_MARK_OFF  // brian.161
#else     // #ifdef SETUP_NO_ANGLE_MARK
#define SETUP_DEFAULT_ANGLE_MARK        SETUP_CUSTOM_ANGLE_MARK_ON
#endif    // #ifdef SETUP_NO_ANGLE_MARK

#define SETUP_DEFAULT_UI_STYLE          SETUP_CUSTOM_UI_STYLE_3  // brian.161

#define SETUP_DEFAULT_PROGRESSIVE_SCAN      SETUP_PROGRESSIVE_SCAN_OFF // Brian0.81
//#define SETUP_DEFAULT_AUDIO_DIGITAL_OUT     SETUP_AUDIO_DIGITAL_OUT_SPDIF_RAW   // Brian0.82
//LLY2.82#define SETUP_DEFAULT_AUDIO_ANALOG_OUT	    SETUP_AUDIO_ANALOG_OUT_51CH  // Brian0.82

// Customer should modify here for region code
#define SETUP_DEFAULT_REGION            REGION_ALL
#define SETUP_DEFAULT_APS_CTL           TRUE
#define SETUP_DEFAULT_PARENTAL_CTL      TRUE

#ifdef   SUPPORT_VCD_CONTROL 
#define SETUP_DEFAULT_VCD_CTL           FALSE   // ** TCH2.74;
#else
#define SETUP_DEFAULT_VCD_CTL           FALSE   // ** TCH2.74; must set FALSE as original setting support VCD playback.
#endif  // #define SUPPORT_VCD_CONTROL 

#define SETUP_DEFAULT_DEBUG_MODE        SETUP_DEBUG_MODE_DSU1_EN 


#define SETUP_DEFAULT_AP_MODE         0


#if     (SELL_DESTINATION == CHINA)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_SIMP_CHINESE
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_CHINESE
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_CHINESE
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_CHINESE
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_ASCII 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_ASCII 	
#elif (SELL_DESTINATION == HONGKONG)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_TRAD_CHINESE
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_CHINESE
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_CHINESE
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_CHINESE
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_ASCII 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_ASCII 
#elif (SELL_DESTINATION == TAIWAN)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_TRAD_CHINESE
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_CHINESE
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_CHINESE
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_CHINESE
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_ASCII 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_ASCII 
#elif (SELL_DESTINATION == BRITISH)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_ENGLISH
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_ENGLISH
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_ENGLISH
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_ENGLISH
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == FRANCE)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_FRENCH
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_FRENCH
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_FRENCH
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_FRENCH
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == GERMANY)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_GERMAN
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_GERMAN
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_GERMAN
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_GERMAN
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == ITALY)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_ITALIAN
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_ITALIAN
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_ITALIAN
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_ITALIAN
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == SPAIN)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_SPANISH
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_SPANISH
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_SPANISH
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_SPANISH
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == PORTUGAL)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_ENGLISH
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_PORTUGUESE
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_PORTUGUESE
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_PORTUGUESE
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == EUROPE)
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_ENGLISH
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_ENGLISH
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_ENGLISH
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_ENGLISH
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN 
#elif (SELL_DESTINATION == JAPAN) // LLY.276-5, for Japanese OSD
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_JAPANESE
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_JAPANESE
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_JAPANESE
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_JAPANESE
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_ASCII 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_ASCII 
#elif (SELL_DESTINATION == KOREA) // Brian1.07, Jeff 20030916 Add for Korean OSD
#define SETUP_DEFAULT_OSD_LANGUAGE      SETUP_LANGUAGE_OSD_KOREAN
#define SETUP_DEFAULT_MENU_LANGUAGE     SETUP_LANGUAGE_MENU_KOREAN
#define SETUP_DEFAULT_AUDIO_LANGUAGE    SETUP_LANGUAGE_AUDIO_KOREAN
#define SETUP_DEFAULT_SPST_LANGUAGE     SETUP_LANGUAGE_SP_KOREAN
//#define SETUP_DEFAULT_EX_SPST_LANGUAGE  SETUP_LANGUAGE_EX_SP_ASCII 
#define SETUP_DEFAULT_ENCODING_LANGUAGE    SETUP_LANGUAGE_ENCODING_ASCII 
#endif



//definition for initializing SETUP status
#define SETUP_POWERON_INITIAL   1
#define SETUP_OTHERS_INITIAL    0

//Internal functions declaration
void    _WriteSetupData(BYTE bSetup, BYTE bDefaultPassword);
void    _ReadSetupData(void);
BYTE    _ConvertBackDoorRegionNum(BYTE bOriginalNum);
BYTE    _ConvertBackDoorRegionToIndex(BYTE bOriginalNum);
WORD    _GetPasswordNumber(void);
void    _SaveDataToSetupInfo(void);
void    _ProcessBackDoor(BYTE bActionMode);
void    _SetMenuEnable(BYTE bMode);
void    _SetBrightnessToIC(void);
void    _SetContrastToIC(void);
void    _SetDNRToIC(void);
void    _SetTVSystemToIC(void);
void    _SetVideoAspectToIC(void);      // TCC276
void    _SetVideoOutputToIC(void);
void    _TransferSetupInfoToIndex(void);
void    _TransferLanguageToSPRM(void);
#ifndef NO_DISC_MODE //CoCo2.37p
void    _TransferOthersMenuLanguageCode(WORD wLanguageCode);
void    _TransferOthersAudioLanguageCode(WORD wLanguageCode);
void    _TransferOthersSPSTLanguageCode(WORD wLanguageCode);
#endif //#ifndef NO_DISC_MODE //CoCo2.37p
WORD    _GetLanguageNumber(void);//(BYTE bID);
void    _ClearAllHighlight(void);
void    _ReloadFontTable(BYTE bLanguage);
void    _ExitBackDoor(void);
void    _ExitSetup(void);
void    _RecoverVariables(void);


//Export APIs
void    SETUP_GDIInit(void);
BIT     SETUP_Initial(void);
BYTE    SETUP_ProcessKey(void);
BYTE    SETUP_InputPassword(BYTE bKey);
BYTE    SETUP_GetMenuInfo(BYTE bIndex, BYTE bInfoType);
void    SETUP_PartialRedraw(DWORD X0, DWORD Y0, DWORD X1, DWORD Y1);
BYTE    SETUP_Recover(BYTE bRecoverRegion);
void    SETUP_Exit(BYTE bExitMode);
void    SETUP_ChangeValue(BYTE bID);
void    SETUP_SetDefaultValue(BYTE bType); // Brian1.24
void    SETUP_Trigger(void);
void    SETUP_AdjustSetting(BYTE bID);
void    SETUP_ConfigOSDRegion(void);
void SETUP_LoadLanguage(void);



typedef enum tagID_LIST
{
    SETUP_ID_BASE=0,
    // Main menu item
    SETUP_MAIN_BASE=SETUP_ID_BASE,
    SETUP_MAIN_LANGUAGE=SETUP_MAIN_BASE,
    SETUP_MAIN_SCREEN,
    SETUP_MAIN_AUDIO,
    SETUP_MAIN_CUSTOM,
    SETUP_MAIN_EXIT,
    // Main->Language sub menu
    SETUP_LANGUAGE_BASE=6,
    SETUP_LANGUAGE_OSD=SETUP_LANGUAGE_BASE,
    SETUP_LANGUAGE_MENU,
    SETUP_LANGUAGE_AUDIO,
    SETUP_LANGUAGE_SUBTITLE,
    //SETUP_LANGUAGE_EX_SUBTITLE,
    SETUP_LANGUAGE_ENCODING,
    // Main->Screen sub menu
    SETUP_SCREEN_BASE=11,
    SETUP_SCREEN_TV_TYPE=SETUP_SCREEN_BASE,
#ifndef NO_SCREEN_SAVER // Brian1.20
    SETUP_SCREEN_SAVER,
#endif
    SETUP_SCREEN_TV_SYSTEM,
    SETUP_SCREEN_VIDEO_OUTPUT,
    //SETUP_SCREEN_PROGRESSIVE_SCAN, // Brian1.06, P-SCAN is integrated into Video Output
    SETUP_SCREEN_BRIGHTNESS,
    SETUP_SCREEN_CONTRAST,
#ifdef SUPPORT_ADJUST_CHROM_PHASE // Brian1.25, Chroma phase
    SETUP_SCREEN_CHROM_PHASE,
#endif
    SETUP_SCREEN_PROGRESSIVE_SCAN, // Brian1.06, P-SCAN is integrated into Video Output, but still need this ID, so move it to the end
    // Main->Audio sub menu
    SETUP_AUDIO_BASE=19,     
    SETUP_AUDIO_DIGITAL_OUT=SETUP_AUDIO_BASE,

#ifndef SUPPORT_2_CHANNEL_ONLY // Brian1.05
    SETUP_AUDIO_ANALOG_OUT,
#endif

    SETUP_AUDIO_DOWNMIX,

#ifndef SUPPORT_2_CHANNEL_ONLY // Brian1.05
    SETUP_AUDIO_PROLOGIC, // Brian1.08
    SETUP_AUDIO_CENTER,   
    SETUP_AUDIO_REAR,     
    SETUP_AUDIO_SUBWOOFER,
#ifndef REMOVE_SETUP_SPEAKER_TEST
    SETUP_AUDIO_SPEAKER_TEST,
#endif
#endif


    SETUP_AUDIO_DNR,      
    SETUP_AUDIO_LPCM,
    SETUP_AUDIO_KARAOKE,
// Brian1.05, still need these ID, but must put it at the end of menu
// so the ID seuqence of real items are continuous

#ifdef SUPPORT_2_CHANNEL_ONLY 
    SETUP_AUDIO_ANALOG_OUT,
    SETUP_AUDIO_PROLOGIC, // Brian1.08. 2 channel has no prologic
    SETUP_AUDIO_CENTER,   
    SETUP_AUDIO_REAR,     
    SETUP_AUDIO_SUBWOOFER,
#ifndef REMOVE_SETUP_SPEAKER_TEST
    SETUP_AUDIO_SPEAKER_TEST,
#endif
#endif
   
    // Main->Custom sub menu
#ifndef IMAGE_FRAME_SETUP //CoCo2.38
    SETUP_CUSTOM_BASE=30,            
    SETUP_CUSTOM_PARENTAL=SETUP_CUSTOM_BASE,        
    SETUP_CUSTOM_CHANGE_PASSWORD, 
    SETUP_CUSTOM_ANGLE_MARK,      
    SETUP_CUSTOM_SMART_PLAY,      
    SETUP_CUSTOM_UI_STYLE,      
#ifndef NO_DRM
    SETUP_CUSTOM_DIVX_VOD,
#endif
    SETUP_CUSTOM_DEFAULT_VALUE,
#endif //IMAGE_FRAME_SETUP

/*
#ifndef SUPPORT_STRING_GENERATOR // Brian1.25
*/

    // Main->Language->OSD Sub menu
    SETUP_LANGUAGE_OSD_BEGIN=37,
    SETUP_LANGUAGE_OSD_BASE=SETUP_LANGUAGE_OSD_BEGIN,                 
    SETUP_LANGUAGE_OSD_ENGLISH=SETUP_LANGUAGE_OSD_BASE,

#if (OSD_LANGUAGE_GROUP == CHINA_AREA_OSD)
 #if (CHINESE_OSD_MODE == SIMPLE_CHINESE)
    SETUP_LANGUAGE_OSD_SIMP_CHINESE, // Simplified Chinese
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_SIMP_CHINESE,
    SETUP_LANGUAGE_OSD_TRAD_CHINESE, // Traditional Chinese
 #elif (CHINESE_OSD_MODE == TRADITIONAL_CHINESE)
    SETUP_LANGUAGE_OSD_TRAD_CHINESE, // Traditional Chinese
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_TRAD_CHINESE,
    SETUP_LANGUAGE_OSD_SIMP_CHINESE, // Simplified Chinese
 #endif
    SETUP_LANGUAGE_OSD_FRENCH,    
    SETUP_LANGUAGE_OSD_GERMAN,    
    SETUP_LANGUAGE_OSD_ITALIAN,   
    SETUP_LANGUAGE_OSD_SPANISH,   
    SETUP_LANGUAGE_OSD_PORTUGUESE,
    SETUP_LANGUAGE_OSD_DUTCH,
    SETUP_LANGUAGE_OSD_POLISH,
    SETUP_LANGUAGE_OSD_JAPANESE,
#elif (OSD_LANGUAGE_GROUP == EUROPE_AREA_OSD)
    SETUP_LANGUAGE_OSD_FRENCH,    
    SETUP_LANGUAGE_OSD_GERMAN,    
    SETUP_LANGUAGE_OSD_ITALIAN,   
    SETUP_LANGUAGE_OSD_SPANISH,   
    SETUP_LANGUAGE_OSD_PORTUGUESE,
    SETUP_LANGUAGE_OSD_DUTCH,
    SETUP_LANGUAGE_OSD_POLISH,
    SETUP_LANGUAGE_OSD_CZECH,
    SETUP_LANGUAGE_OSD_RUSSIAN,
    SETUP_LANGUAGE_OSD_GREECE,
    SETUP_LANGUAGE_OSD_TURKEY,
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_TURKEY,
    SETUP_LANGUAGE_OSD_TRAD_CHINESE, // Traditional Chinese
    SETUP_LANGUAGE_OSD_SIMP_CHINESE, // Simplified Chinese
	SETUP_LANGUAGE_OSD_JAPANESE,
#elif (OSD_LANGUAGE_GROUP == JAPAN_AREA_OSD) 
    SETUP_LANGUAGE_OSD_JAPANESE,
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_JAPANESE,
    SETUP_LANGUAGE_OSD_FRENCH,    
    SETUP_LANGUAGE_OSD_GERMAN,    
    SETUP_LANGUAGE_OSD_ITALIAN,   
    SETUP_LANGUAGE_OSD_SPANISH,   
    SETUP_LANGUAGE_OSD_PORTUGUESE,
    SETUP_LANGUAGE_OSD_DUTCH,
    SETUP_LANGUAGE_OSD_POLISH,
    SETUP_LANGUAGE_OSD_TRAD_CHINESE, // Traditional Chinese
    SETUP_LANGUAGE_OSD_SIMP_CHINESE, // Simplified Chinese
#elif (OSD_LANGUAGE_GROUP == KOREAN_AREA_OSD) 
    SETUP_LANGUAGE_OSD_KOREAN,
    SETUP_LANGUAGE_OSD_END=SETUP_LANGUAGE_OSD_KOREAN,
    SETUP_LANGUAGE_OSD_FRENCH,    
    SETUP_LANGUAGE_OSD_GERMAN,    
    SETUP_LANGUAGE_OSD_ITALIAN,   
    SETUP_LANGUAGE_OSD_SPANISH,   
    SETUP_LANGUAGE_OSD_PORTUGUESE,
    SETUP_LANGUAGE_OSD_DUTCH,
    SETUP_LANGUAGE_OSD_POLISH,
    SETUP_LANGUAGE_OSD_JAPANESE,
#endif

/*
#else //#ifndef SUPPORT_STRING_GENERATOR

#include "langid.h" // the Setup OSD language ID is generated by String Tool

#endif //#ifndef SUPPORT_STRING_GENERATOR
*/


    // Main->Language->Menu Sub menu
	SETUP_LANGUAGE_MENU_BEGIN=50,
    SETUP_LANGUAGE_MENU_BASE=SETUP_LANGUAGE_MENU_BEGIN,      
    SETUP_LANGUAGE_MENU_ENGLISH=SETUP_LANGUAGE_MENU_BASE,   
    SETUP_LANGUAGE_MENU_CHINESE,   
    SETUP_LANGUAGE_MENU_JAPANESE,  
    SETUP_LANGUAGE_MENU_FRENCH,    
    SETUP_LANGUAGE_MENU_GERMAN,    
    SETUP_LANGUAGE_MENU_ITALIAN,   
    SETUP_LANGUAGE_MENU_SPANISH,   
    SETUP_LANGUAGE_MENU_PORTUGUESE,
    SETUP_LANGUAGE_MENU_HINDI,     
    SETUP_LANGUAGE_MENU_THAI,      
    SETUP_LANGUAGE_MENU_RUSSIAN,   
    SETUP_LANGUAGE_MENU_KOREAN,    
    SETUP_LANGUAGE_MENU_OTHERS,
	SETUP_LANGUAGE_MENU_END=SETUP_LANGUAGE_MENU_OTHERS,
    // Main->Language->Audio Sub menu
	SETUP_LANGUAGE_AUDIO_BEGIN=65,
    SETUP_LANGUAGE_AUDIO_BASE=SETUP_LANGUAGE_AUDIO_BEGIN,      
    SETUP_LANGUAGE_AUDIO_ENGLISH=SETUP_LANGUAGE_AUDIO_BASE,   
    SETUP_LANGUAGE_AUDIO_CHINESE,   
    SETUP_LANGUAGE_AUDIO_JAPANESE,  
    SETUP_LANGUAGE_AUDIO_FRENCH,    
    SETUP_LANGUAGE_AUDIO_GERMAN,    
    SETUP_LANGUAGE_AUDIO_ITALIAN,   
    SETUP_LANGUAGE_AUDIO_SPANISH,   
    SETUP_LANGUAGE_AUDIO_PORTUGUESE,
    SETUP_LANGUAGE_AUDIO_HINDI,     
    SETUP_LANGUAGE_AUDIO_THAI,      
    SETUP_LANGUAGE_AUDIO_RUSSIAN,   
    SETUP_LANGUAGE_AUDIO_KOREAN,    
    SETUP_LANGUAGE_AUDIO_OTHERS,
	SETUP_LANGUAGE_AUDIO_END=SETUP_LANGUAGE_AUDIO_OTHERS,
    // Main->Language->Subtitle Sub menu
	SETUP_LANGUAGE_SP_BEGIN=80,
    SETUP_LANGUAGE_SP_BASE=SETUP_LANGUAGE_SP_BEGIN,      
    SETUP_LANGUAGE_SP_ENGLISH=SETUP_LANGUAGE_SP_BASE,   
    SETUP_LANGUAGE_SP_CHINESE,   
    SETUP_LANGUAGE_SP_JAPANESE,  
    SETUP_LANGUAGE_SP_FRENCH,    
    SETUP_LANGUAGE_SP_GERMAN,    
    SETUP_LANGUAGE_SP_ITALIAN,   
    SETUP_LANGUAGE_SP_SPANISH,   
    SETUP_LANGUAGE_SP_PORTUGUESE,
    SETUP_LANGUAGE_SP_HINDI,     
    SETUP_LANGUAGE_SP_THAI,      
    SETUP_LANGUAGE_SP_RUSSIAN,   
    SETUP_LANGUAGE_SP_KOREAN,    
    SETUP_LANGUAGE_SP_OTHERS,
    SETUP_LANGUAGE_SP_OFF,
    SETUP_LANGUAGE_SP_END=SETUP_LANGUAGE_SP_OFF,
/*
    // Main->Language->Subtitle Sub menu
    SETUP_LANGUAGE_EX_SP_BEGIN=96,
    SETUP_LANGUAGE_EX_SP_BASE=SETUP_LANGUAGE_EX_SP_BEGIN,      
    SETUP_LANGUAGE_EX_SP_ASCII=SETUP_LANGUAGE_EX_SP_BASE,   
    SETUP_LANGUAGE_EX_SP_WESTERN_EUROPEAN,   
    SETUP_LANGUAGE_EX_SP_CENTRAL_EUROPEAN,   
    SETUP_LANGUAGE_EX_SP_CYRILLIC,
    SETUP_LANGUAGE_EX_SP_CP1250,
    SETUP_LANGUAGE_EX_SP_GREEK,
    // Damon2.51, for Hebrew
    SETUP_LANGUAGE_EX_SP_HEBREW,
    SETUP_LANGUAGE_EX_SP_TURKISH,
    SETUP_LANGUAGE_EX_SP_END=SETUP_LANGUAGE_EX_SP_TURKISH,
*/
    // Main->Language->Encoding menu
    SETUP_LANGUAGE_ENCODING_BEGIN=96,
    SETUP_LANGUAGE_ENCODING_BASE=SETUP_LANGUAGE_ENCODING_BEGIN,      
    SETUP_LANGUAGE_ENCODING_ASCII=SETUP_LANGUAGE_ENCODING_BASE,   
#ifdef SUPPORT_CHAR_ENCODING_WESTERN_EUROPEAN    
    SETUP_LANGUAGE_ENCODING_WESTERN_EUROPEAN,   
#endif   
#ifdef SUPPORT_CHAR_ENCODING_CENTRAL_EUROPEAN
    SETUP_LANGUAGE_ENCODING_CENTRAL_EUROPEAN,       
#endif
#ifdef SUPPORT_CHAR_ENCODING_GREEK
    SETUP_LANGUAGE_ENCODING_GREEK,
#endif
#ifdef SUPPORT_CHAR_ENCODING_HEBREW    
    // Damon2.51, for Hebrew
    SETUP_LANGUAGE_ENCODING_HEBREW,
#endif
#ifdef SUPPORT_CHAR_ENCODING_TURKISH    
    SETUP_LANGUAGE_ENCODING_TURKISH,
#endif
#ifdef SUPPORT_CHAR_ENCODING_CP1250
    SETUP_LANGUAGE_ENCODING_CP1250,
#endif
#ifdef SUPPORT_CHAR_ENCODING_CYRILLIC
    SETUP_LANGUAGE_ENCODING_CYRILLIC,    
#endif
#ifdef SUPPORT_CHAR_ENCODING_CHINESE
    SETUP_LANGUAGE_ENCODING_TWN_UNICODE,
#endif
#ifdef SUPPORT_CHAR_ENCODING_BIG5
    SETUP_LANGUAGE_ENCODING_TWN_BIG5,
#endif
#ifdef SUPPORT_CHAR_ENCODING_JAPANESE
    SETUP_LANGUAGE_ENCODING_JPN_UNICODE,     
#endif  
#ifdef SUPPORT_CHAR_ENCODING_SHIFT_JIS
    SETUP_LANGUAGE_ENCODING_JPN_SHIFT_JIS,     
#endif  
    SETUP_LANGUAGE_ENCODING_END,
    // Main->Screen->TV Type
	SETUP_SCREEN_TV_TYPE_BEGIN=107,
    SETUP_SCREEN_TV_TYPE_BASE=SETUP_SCREEN_TV_TYPE_BEGIN,
    SETUP_SCREEN_TV_TYPE_PS=SETUP_SCREEN_TV_TYPE_BASE,  
    SETUP_SCREEN_TV_TYPE_LB,  
    SETUP_SCREEN_TV_TYPE_WIDE,
	SETUP_SCREEN_TV_TYPE_END=SETUP_SCREEN_TV_TYPE_WIDE,
#ifndef NO_SCREEN_SAVER // Brian1.20
    // Main->Screen->Screen Saver
	SETUP_SCREEN_SAVER_BEGIN=110,
    SETUP_SCREEN_SAVER_BASE=SETUP_SCREEN_SAVER_BEGIN,
    SETUP_SCREEN_SAVER_ON=SETUP_SCREEN_SAVER_BASE,  
    SETUP_SCREEN_SAVER_OFF, 
	SETUP_SCREEN_SAVER_END=SETUP_SCREEN_SAVER_OFF,
#endif
    // Main->Screen->TV System
	SETUP_SCREEN_TV_SYSTEM_BEGIN=112,	// this is for KEY_TV_MODE
    SETUP_SCREEN_TV_SYSTEM_BASE=SETUP_SCREEN_TV_SYSTEM_BEGIN,
    SETUP_SCREEN_TV_SYSTEM_NTSC=SETUP_SCREEN_TV_SYSTEM_BASE, 
    SETUP_SCREEN_TV_SYSTEM_PAL,  
    SETUP_SCREEN_TV_SYSTEM_AUTO, 
    SETUP_SCREEN_TV_SYSTEM_PAL_M,
    SETUP_SCREEN_TV_SYSTEM_PAL_N,
#ifdef SUPPORT_EXTRA_PAL_MODE
	SETUP_SCREEN_TV_SYSTEM_END=SETUP_SCREEN_TV_SYSTEM_PAL_N, // this is for KEY_TV_MODE
#else
    SETUP_SCREEN_TV_SYSTEM_END=SETUP_SCREEN_TV_SYSTEM_AUTO,// this is for KEY_TV_MODE
#endif
    // Main->Screen->Video Output
	SETUP_SCREEN_VIDEO_OUTPUT_BEGIN=117,
    SETUP_SCREEN_VIDEO_OUTPUT_BASE=SETUP_SCREEN_VIDEO_OUTPUT_BEGIN,

#ifdef SUPPORT_SCART_IF // Support SCART 
    // **** the sequence must match the mneu structure in OSD3.h
        SETUP_SCREEN_VIDEO_OUTPUT_NORMAL=SETUP_SCREEN_VIDEO_OUTPUT_BASE,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB_PSCAN,
    SETUP_SCREEN_VIDEO_OUTPUT_YUV,
    SETUP_SCREEN_VIDEO_OUTPUT_YUV_PSCAN,
    SETUP_SCREEN_VIDEO_OUTPUT_VGA,
    SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_RGB_PSCAN,
#elif defined(NO_PSCAN_OUTPUT)  
    SETUP_SCREEN_VIDEO_OUTPUT_NORMAL=SETUP_SCREEN_VIDEO_OUTPUT_BASE,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB,
    SETUP_SCREEN_VIDEO_OUTPUT_YUV,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB_PSCAN,    
    SETUP_SCREEN_VIDEO_OUTPUT_YUV_PSCAN,
    SETUP_SCREEN_VIDEO_OUTPUT_VGA,
    SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_YUV,
/*
#elif defined(SETUP_NO_RGB_OUTPUT)
    // **** the sequence doesn't match OSD3.h, but seems no body use this setting, so ignore it for now
    // Don't use this
	SETUP_SCREEN_VIDEO_OUTPUT_NORMAL=SETUP_SCREEN_VIDEO_OUTPUT_BASE,
	SETUP_SCREEN_VIDEO_OUTPUT_YUV,
	SETUP_SCREEN_VIDEO_OUTPUT_RGB,
    SETUP_SCREEN_VIDEO_OUTPUT_VGA,
    SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_YUV,
*/
#else
    // This is what we use now
    // the seuqence must match the mneu structure in OSD3.h
	SETUP_SCREEN_VIDEO_OUTPUT_NORMAL=SETUP_SCREEN_VIDEO_OUTPUT_BASE,
    SETUP_SCREEN_VIDEO_OUTPUT_YUV,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB,
    SETUP_SCREEN_VIDEO_OUTPUT_YUV_PSCAN,
    SETUP_SCREEN_VIDEO_OUTPUT_RGB_PSCAN,
    SETUP_SCREEN_VIDEO_OUTPUT_VGA,
#ifdef NO_VGA_OUTPUT // RELEASE_SETTING
    //SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_RGB,
    SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_RGB_PSCAN,
#else
    SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_VGA, 
#endif

#endif
	//SETUP_SCREEN_VIDEO_OUTPUT_END=SETUP_SCREEN_VIDEO_OUTPUT_VGA, //SETUP_SCREEN_VIDEO_OUTPUT_NORMAL,
    
    // Main->Screen->Progressive
    SETUP_PROGRESSIVE_SCAN_BEGIN=124,
    SETUP_PROGRESSIVE_SCAN_BASE=SETUP_PROGRESSIVE_SCAN_BEGIN,
    SETUP_PROGRESSIVE_SCAN_ON=SETUP_PROGRESSIVE_SCAN_BASE,
    SETUP_PROGRESSIVE_SCAN_OFF,
    SETUP_PROGRESSIVE_SCAN_END=SETUP_PROGRESSIVE_SCAN_OFF,
    // Main->Screen->Brightness
	SETUP_SCREEN_BRIGHTNESS_BEGIN=126,
    SETUP_SCREEN_BRIGHTNESS_BASE=SETUP_SCREEN_BRIGHTNESS_BEGIN,  
    SETUP_SCREEN_BRIGHTNESS_NORMAL=SETUP_SCREEN_BRIGHTNESS_BASE,
    SETUP_SCREEN_BRIGHTNESS_BRIGHT,
    SETUP_SCREEN_BRIGHTNESS_SOFT,
	SETUP_SCREEN_BRIGHTNESS_END=SETUP_SCREEN_BRIGHTNESS_SOFT,
    // Main->Screen->Contrast
	SETUP_SCREEN_CONTRAST_BEGIN=130,
    SETUP_SCREEN_CONTRAST_BASE=SETUP_SCREEN_CONTRAST_BEGIN,  
    SETUP_SCREEN_CONTRAST_MINUS4=SETUP_SCREEN_CONTRAST_BASE,
    SETUP_SCREEN_CONTRAST_MINUS3,
    SETUP_SCREEN_CONTRAST_MINUS2,
    SETUP_SCREEN_CONTRAST_MINUS1,
    SETUP_SCREEN_CONTRAST_0,     
    SETUP_SCREEN_CONTRAST_PLUS1, 
    SETUP_SCREEN_CONTRAST_PLUS2, 
    SETUP_SCREEN_CONTRAST_PLUS3, 
    SETUP_SCREEN_CONTRAST_PLUS4,
	SETUP_SCREEN_CONTRAST_END=SETUP_SCREEN_CONTRAST_PLUS4,

	SETUP_AUDIO_OUTPUT, //just used as parameter for SETUP_ChangeValue()
    // Main->Audio->Digital Out
	SETUP_AUDIO_OUTPUT_BEGIN=140,	// this is for KEY_AUDIO_OUTPUT
	SETUP_AUDIO_DIGITAL_OUT_BEGIN=SETUP_AUDIO_OUTPUT_BEGIN,
    SETUP_AUDIO_DIGITAL_OUT_BASE=SETUP_AUDIO_DIGITAL_OUT_BEGIN,     
    SETUP_AUDIO_DIGITAL_OUT_SPDIF_PCM=SETUP_AUDIO_DIGITAL_OUT_BASE,      
    SETUP_AUDIO_DIGITAL_OUT_SPDIF_RAW, 
    SETUP_AUDIO_DIGITAL_OUT_OFF,
	SETUP_AUDIO_DIGITAL_OUT_END=SETUP_AUDIO_DIGITAL_OUT_OFF,
    // Main->Audio->Analog Out
	SETUP_AUDIO_ANALOG_OUT_BEGIN=145,
    SETUP_AUDIO_ANALOG_OUT_BASE=SETUP_AUDIO_ANALOG_OUT_BEGIN,     
    SETUP_AUDIO_ANALOG_OUT_2CH=SETUP_AUDIO_ANALOG_OUT_BASE,
#ifdef SUPPORT_2_CHANNEL_ONLY

#ifdef SUPPORT_ANALOG_OUTPUT_OFF // Brian1.10
    SETUP_AUDIO_ANALOG_OUT_OFF, 
    SETUP_AUDIO_ANALOG_OUT_51CH, // not appear in menu
	SETUP_AUDIO_ANALOG_OUT_END=SETUP_AUDIO_ANALOG_OUT_OFF, //SETUP_AUDIO_ANALOG_OUT_OFF,
	SETUP_AUDIO_OUTPUT_END=SETUP_AUDIO_ANALOG_OUT_OFF, //SETUP_AUDIO_ANALOG_OUT_OFF, // this is for KEY_AUDIO_OUTPUT
#else //SUPPORT_ANALOG_OUTPUT_OFF
    SETUP_AUDIO_ANALOG_OUT_OFF,  // not appear in menu
    SETUP_AUDIO_ANALOG_OUT_51CH, // not appear in menu
	SETUP_AUDIO_ANALOG_OUT_END=SETUP_AUDIO_ANALOG_OUT_2CH, //SETUP_AUDIO_ANALOG_OUT_OFF,
	SETUP_AUDIO_OUTPUT_END=SETUP_AUDIO_ANALOG_OUT_2CH, //SETUP_AUDIO_ANALOG_OUT_OFF, // this is for KEY_AUDIO_OUTPUT
#endif // SUPPORT_ANALOG_OUTPUT_OFF

#else // SUPPORT_2_CHANNEL_ONLY

#ifdef SUPPORT_ANALOG_OUTPUT_OFF
    SETUP_AUDIO_ANALOG_OUT_51CH,
    SETUP_AUDIO_ANALOG_OUT_OFF,
	SETUP_AUDIO_ANALOG_OUT_END=SETUP_AUDIO_ANALOG_OUT_OFF, //SETUP_AUDIO_ANALOG_OUT_OFF,
	SETUP_AUDIO_OUTPUT_END=SETUP_AUDIO_ANALOG_OUT_OFF, //SETUP_AUDIO_ANALOG_OUT_OFF, // this is for KEY_AUDIO_OUTPUT
#else
    SETUP_AUDIO_ANALOG_OUT_51CH,
    SETUP_AUDIO_ANALOG_OUT_OFF, // not appear in menu
	SETUP_AUDIO_ANALOG_OUT_END=SETUP_AUDIO_ANALOG_OUT_51CH, //SETUP_AUDIO_ANALOG_OUT_OFF,
	SETUP_AUDIO_OUTPUT_END=SETUP_AUDIO_ANALOG_OUT_51CH, //SETUP_AUDIO_ANALOG_OUT_OFF, // this is for KEY_AUDIO_OUTPUT
#endif

#endif // SUPPORT_2_CHANNEL_ONLY


    // Main->Audio->DownMix
	SETUP_AUDIO_DOWNMIX_BEGIN=148,
    SETUP_AUDIO_DOWNMIX_BASE=SETUP_AUDIO_DOWNMIX_BEGIN,
    SETUP_AUDIO_DOWNMIX_LORO=SETUP_AUDIO_DOWNMIX_BASE,
    SETUP_AUDIO_DOWNMIX_LTRT,
	SETUP_AUDIO_DOWNMIX_END=SETUP_AUDIO_DOWNMIX_LTRT,


    // Main->Audio->Center
	SETUP_AUDIO_CENTER_BEGIN=150,
    SETUP_AUDIO_CENTER_BASE=SETUP_AUDIO_CENTER_BEGIN,
    SETUP_AUDIO_CENTER_ON=SETUP_AUDIO_CENTER_BASE,
    SETUP_AUDIO_CENTER_OFF,
	SETUP_AUDIO_CENTER_END=SETUP_AUDIO_CENTER_OFF,
    // Main->Audio->Rear
	SETUP_AUDIO_REAR_BEGIN=152,
    SETUP_AUDIO_REAR_BASE=SETUP_AUDIO_REAR_BEGIN,
    SETUP_AUDIO_REAR_ON=SETUP_AUDIO_REAR_BASE,
    SETUP_AUDIO_REAR_OFF,
	SETUP_AUDIO_REAR_END=SETUP_AUDIO_REAR_OFF,
    // Main->Audio->Subwoofer
	SETUP_AUDIO_SUBWOOFER_BEGIN=154,
    SETUP_AUDIO_SUBWOOFER_BASE=SETUP_AUDIO_SUBWOOFER_BEGIN,
    SETUP_AUDIO_SUBWOOFER_ON=SETUP_AUDIO_SUBWOOFER_BASE,
    SETUP_AUDIO_SUBWOOFER_OFF,
	SETUP_AUDIO_SUBWOOFER_END=SETUP_AUDIO_SUBWOOFER_OFF,
#ifndef REMOVE_SETUP_SPEAKER_TEST
    // Main->Audio->Speaker Test
    SETUP_AUDIO_SPEAKER_TEST_BASE=156,
    SETUP_AUDIO_SPEAKER_TEST_OFF=SETUP_AUDIO_SPEAKER_TEST_BASE,
    SETUP_AUDIO_SPEAKER_TEST_SEPARATE_LINE,
    SETUP_AUDIO_SPEAKER_TEST_AUTO,
    SETUP_AUDIO_SPEAKER_TEST_LEFT,
    SETUP_AUDIO_SPEAKER_TEST_RIGHT,
    SETUP_AUDIO_SPEAKER_TEST_CENTER,
    SETUP_AUDIO_SPEAKER_TEST_LS,
    SETUP_AUDIO_SPEAKER_TEST_RS,
    SETUP_AUDIO_SPEAKER_TEST_SW,
#endif

    // Main->Custom->Parental Control
	SETUP_CUSTOM_PC_LEVEL_BEGIN=165,
    SETUP_CUSTOM_PC_LEVEL_BASE=SETUP_CUSTOM_PC_LEVEL_BEGIN,
    SETUP_CUSTOM_PC_LEVEL_1=SETUP_CUSTOM_PC_LEVEL_BASE,
    SETUP_CUSTOM_PC_LEVEL_2,
    SETUP_CUSTOM_PC_LEVEL_3,
    SETUP_CUSTOM_PC_LEVEL_4,
    SETUP_CUSTOM_PC_LEVEL_5,
    SETUP_CUSTOM_PC_LEVEL_6,
    SETUP_CUSTOM_PC_LEVEL_7,
    SETUP_CUSTOM_PC_LEVEL_8,
    SETUP_CUSTOM_PC_LEVEL_OFF,
	SETUP_CUSTOM_PC_LEVEL_END=SETUP_CUSTOM_PC_LEVEL_OFF,

#ifndef IMAGE_FRAME_SETUP //CoCo2.38
    // Main->Custom->UI Style
	SETUP_CUSTOM_UI_STYLE_BEGIN=174,
    SETUP_CUSTOM_UI_STYLE_BASE=SETUP_CUSTOM_UI_STYLE_BEGIN,
    SETUP_CUSTOM_UI_STYLE_1=SETUP_CUSTOM_UI_STYLE_BASE,
    SETUP_CUSTOM_UI_STYLE_2,
    SETUP_CUSTOM_UI_STYLE_3,
    SETUP_CUSTOM_UI_STYLE_4,
	SETUP_CUSTOM_UI_STYLE_END=SETUP_CUSTOM_UI_STYLE_4,
#endif

    // Main->Custom->Smart Play
        SETUP_CUSTOM_SMART_PLAY_BEGIN=178,
    SETUP_CUSTOM_SMART_PLAY_BASE=SETUP_CUSTOM_SMART_PLAY_BEGIN,
    SETUP_CUSTOM_SMART_PLAY_ON=SETUP_CUSTOM_SMART_PLAY_BASE,
    SETUP_CUSTOM_SMART_PLAY_OFF,
        SETUP_CUSTOM_SMART_PLAY_END=SETUP_CUSTOM_SMART_PLAY_OFF,

    // Main->Custom->Angle Mark
	SETUP_CUSTOM_ANGLE_MARK_BEGIN=180,
    SETUP_CUSTOM_ANGLE_MARK_BASE=SETUP_CUSTOM_ANGLE_MARK_BEGIN,
    SETUP_CUSTOM_ANGLE_MARK_ON=SETUP_CUSTOM_ANGLE_MARK_BASE,
    SETUP_CUSTOM_ANGLE_MARK_OFF,
	SETUP_CUSTOM_ANGLE_MARK_END=SETUP_CUSTOM_ANGLE_MARK_OFF,

    // Main->Custom->Default
        SETUP_CUSTOM_DEFAULT_VALUE_BASE=182,
        SETUP_CUSTOM_DEFAULT_VALUE_READ=SETUP_CUSTOM_DEFAULT_VALUE_BASE,

	SETUP_AUDIO_LPCM_BEGIN=183,
	SETUP_AUDIO_LPCM_BASE=SETUP_AUDIO_LPCM_BEGIN,
	SETUP_AUDIO_LPCM_48K=SETUP_AUDIO_LPCM_BASE,
	SETUP_AUDIO_LPCM_96K,
	SETUP_AUDIO_LPCM_END=SETUP_AUDIO_LPCM_96K,

	SETUP_AUDIO_DNR_BEGIN=185,
	SETUP_AUDIO_DNR_BASE = SETUP_AUDIO_DNR_BEGIN,
#ifdef SUPPORT_DNR_ON_OFF // Brian1.25
	SETUP_AUDIO_DNR_8=SETUP_AUDIO_DNR_BASE,
    SETUP_AUDIO_DNR_0,
    // the following IDs are for compile issue in this case
	SETUP_AUDIO_DNR_1,
	SETUP_AUDIO_DNR_2,
	SETUP_AUDIO_DNR_3,
	SETUP_AUDIO_DNR_4,
	SETUP_AUDIO_DNR_5,
	SETUP_AUDIO_DNR_6,
	SETUP_AUDIO_DNR_7,
	SETUP_AUDIO_DNR_END=SETUP_AUDIO_DNR_0,
#else
	SETUP_AUDIO_DNR_0=SETUP_AUDIO_DNR_BASE,
	SETUP_AUDIO_DNR_1,
	SETUP_AUDIO_DNR_2,
	SETUP_AUDIO_DNR_3,
	SETUP_AUDIO_DNR_4,
	SETUP_AUDIO_DNR_5,
	SETUP_AUDIO_DNR_6,
	SETUP_AUDIO_DNR_7,
	SETUP_AUDIO_DNR_8,
	SETUP_AUDIO_DNR_END=SETUP_AUDIO_DNR_8,
#endif


	SETUP_AUDIO_KARAOKE_BEGIN=194,
	SETUP_AUDIO_KARAOKE_BASE=SETUP_AUDIO_KARAOKE_BEGIN,
	SETUP_AUDIO_KARAOKE_ON=SETUP_AUDIO_KARAOKE_BASE,
	SETUP_AUDIO_KARAOKE_OFF,
	SETUP_AUDIO_KARAOKE_END=SETUP_AUDIO_KARAOKE_OFF,


	//for back door
	SETUP_BACK_DOOR_BASE=206,
	SETUP_BACK_DOOR_REGION=SETUP_BACK_DOOR_BASE,
	SETUP_BACK_DOOR_DEBUG_MODE,

    // Brian1.08
    // Main->Audio->PRO LOGIC
    SETUP_AUDIO_PROLOGIC_BEGIN=202,
	SETUP_AUDIO_PROLOGIC_BASE = SETUP_AUDIO_PROLOGIC_BEGIN,
	SETUP_AUDIO_PROLOGIC_PROLOGIC=SETUP_AUDIO_PROLOGIC_BASE,
	SETUP_AUDIO_PROLOGIC_VIRTUAL,
	SETUP_AUDIO_PROLOGIC_MUSIC,
	SETUP_AUDIO_PROLOGIC_MOVIE,
	SETUP_AUDIO_PROLOGIC_MATRIX,
    SETUP_AUDIO_PROLOGIC_OFF,
	SETUP_AUDIO_PROLOGIC_END=SETUP_AUDIO_PROLOGIC_OFF,

#ifdef SUPPORT_ADJUST_CHROM_PHASE // Brian1.25, Chroma phase
	SETUP_SCREEN_CHROM_PHASE_BEGIN=212,
    SETUP_SCREEN_CHROM_PHASE_BASE=SETUP_SCREEN_CHROM_PHASE_BEGIN,  
    SETUP_SCREEN_CHROM_PHASE_MINUS6=SETUP_SCREEN_CHROM_PHASE_BASE, 
    SETUP_SCREEN_CHROM_PHASE_MINUS5,
    SETUP_SCREEN_CHROM_PHASE_MINUS4,
    SETUP_SCREEN_CHROM_PHASE_MINUS3,    
    SETUP_SCREEN_CHROM_PHASE_MINUS2,
    SETUP_SCREEN_CHROM_PHASE_MINUS1,
    SETUP_SCREEN_CHROM_PHASE_0,  
    SETUP_SCREEN_CHROM_PHASE_PLUS1, 
    SETUP_SCREEN_CHROM_PHASE_PLUS2, 
    SETUP_SCREEN_CHROM_PHASE_PLUS3, 
    SETUP_SCREEN_CHROM_PHASE_PLUS4,
    SETUP_SCREEN_CHROM_PHASE_PLUS5, 
    SETUP_SCREEN_CHROM_PHASE_PLUS6,   
	SETUP_SCREEN_CHROM_PHASE_END=SETUP_SCREEN_CHROM_PHASE_PLUS6,	
#endif	

	// temp, for compiling issue, don't care its value
    // Debug Mode
	SETUP_DEBUG_MODE_BEGIN,
    SETUP_DEBUG_MODE_BASE=SETUP_DEBUG_MODE_BEGIN,  
    SETUP_DEBUG_MODE_NONE,
    SETUP_DEBUG_MODE_DSU1_EN,
    SETUP_DEBUG_MODE_UART1_EN,
    SETUP_DEBUG_MODE_DSU1_UART1_EN,
    SETUP_DEBUG_MODE_DSU1_UART2_EN,
	SETUP_DEBUG_MODE_END=SETUP_DEBUG_MODE_DSU1_UART2_EN,	
    // put these at the end of the list
	SETUP_AUDIO_OUTPUT_SPDIF_PCM,
	SETUP_AUDIO_OUTPUT_SPDIF_RAW,
	SETUP_AUDIO_OUTPUT_51CH,
	SETUP_AUDIO_OUTPUT_2CH

} ID_LIST;



// MenuInfo structure records the status of menu.
typedef struct stMENU_INFO
{
    BYTE        bItem;          // Current item
    BYTE        bDownNext;      // Down item
    BYTE        bRightNext;     // Right item
    BYTE        bParentID;      // Parent's ID
    BYTE        bMsg;           // Message
    BYTE        bValueNum;      // Number of values
} MENU_INFO, *pMENU_INFO;

#define SETUP_BACK_DOOR

#include "storage.h"

#ifdef IMAGE_FRAME_SETUP //CoCo2.38
#include "dvdsetup.h"
#include "dvdsetup_op.h"
#endif

#ifdef  MAIN_SETUP_DECLARE
#ifndef RELEASE_SETTING
BYTE _bBackDoor[] = {SETUP_BACK_DOOR_REGION, SETUP_BACK_DOOR_DEBUG_MODE}; 
#else
BYTE _bBackDoor[] = {SETUP_BACK_DOOR_DEBUG_MODE}; 
#endif
#endif  // MAIN_SETUP_DECLARE



//////////////           Palette & Color          //////////////////////////

#define OSDMENU_ENTRY_START               GDI_GENERAL_UI_PALETTE_INDEX_START
#define OSDMENU_ENTRY_MENU_COLOR_BRIGHT			(OSDMENU_ENTRY_START)
#define OSDMENU_ENTRY_MENU_COLOR_DARK			(OSDMENU_ENTRY_MENU_COLOR_BRIGHT+1)
#define OSDMENU_ENTRY_MENU_COLOR_CENTER			(OSDMENU_ENTRY_MENU_COLOR_DARK+1)
#define OSDMENU_ENTRY_TEXT_COLOR_NORMAL			(OSDMENU_ENTRY_MENU_COLOR_CENTER+1)
#define OSDMENU_ENTRY_TEXT_COLOR_DISABLE		(OSDMENU_ENTRY_TEXT_COLOR_NORMAL+1)
#define OSDMENU_ENTRY_DESC_TEXT_COLOR			(OSDMENU_ENTRY_TEXT_COLOR_DISABLE+1)
// item normal color must be the same as menu center color, so use the same entry index  
#define OSDMENU_ENTRY_ITEM_COLOR_NORMAL			OSDMENU_ENTRY_MENU_COLOR_CENTER
#define OSDMENU_ENTRY_ITEM_COLOR_SELECT			(OSDMENU_ENTRY_DESC_TEXT_COLOR+1)
#define OSDMENU_ENTRY_ITEM_COLOR_HIGHLIGHT		(OSDMENU_ENTRY_ITEM_COLOR_SELECT+1)
#define OSDMENU_ENTRY_LAST                              (OSDMENU_ENTRY_ITEM_COLOR_HIGHLIGHT)

#define OSDSETUP_ENTRY_START                    (OSDMENU_ENTRY_LAST+1) 
#define OSDSETUP_ENTRY_COLOR_TOP_BANNER         (OSDSETUP_ENTRY_START)
#define OSDSETUP_ENTRY_COLOR_TOP_BANNER_TEXT    (OSDSETUP_ENTRY_COLOR_TOP_BANNER+1)
#define OSDSETUP_ENTRY_COLOR_BOTTOM_BANNER      (OSDSETUP_ENTRY_COLOR_TOP_BANNER_TEXT+1)
#define OSDSETUP_ENTRY_COLOR_BOTTOM_BANNER_TEXT (OSDSETUP_ENTRY_COLOR_BOTTOM_BANNER+1)
#define OSDSETUP_ENTRY_CENTER_COLOR_BG          (OSDSETUP_ENTRY_COLOR_BOTTOM_BANNER_TEXT+1)
#define OSDSETUP_ENTRY_COLOR_WHITE              (OSDSETUP_ENTRY_CENTER_COLOR_BG+1)
#define OSDSETUP_ENTRY_COLOR_ORANGE             (OSDSETUP_ENTRY_COLOR_WHITE+1)

#define OSDSETUP_ENTRY_FRAME_BRIGHT             (OSDSETUP_ENTRY_COLOR_ORANGE+1)
#define OSDSETUP_ENTRY_FRAME_DARK               (OSDSETUP_ENTRY_FRAME_BRIGHT+1)
#define OSDSETUP_ENTRY_FRAME_CENTER             (OSDSETUP_ENTRY_FRAME_DARK+1)

#define OSDSETUP_ENTRY_HELP_COLOR_BG            (OSDSETUP_ENTRY_FRAME_CENTER+1)
#define OSDSETUP_ENTRY_ICON_COLOR_BG            (OSDSETUP_ENTRY_HELP_COLOR_BG+1)
#define OSDSETUP_ENTRY_SPEAKER_HIGHLIGHT        (OSDSETUP_ENTRY_ICON_COLOR_BG+1)
#define OSDSETUP_ENTRY_ICON_RECT                (OSDSETUP_ENTRY_SPEAKER_HIGHLIGHT+1)
#define OSDSETUP_ENTRY_ICON_NORMAL              (OSDSETUP_ENTRY_ICON_RECT+1)
#define OSDSETUP_ENTRY_ICON_OVER                (OSDSETUP_ENTRY_ICON_NORMAL+1)
#define OSDSETUP_ENTRY_ICON_DOWN                (OSDSETUP_ENTRY_ICON_OVER+1)

#ifdef REMOVE_SETUP_ICON
#define OSDSETUP_ENTRY_ICON_COLOR_ORANGE        (OSDSETUP_ENTRY_ICON_DOWN+1)
#define OSDSETUP_ENTRY_ICON_COLOR_BLUE          (OSDSETUP_ENTRY_ICON_COLOR_ORANGE+1)
#define OSDSETUP_ENTRY_ICON_COLOR_RED           (OSDSETUP_ENTRY_ICON_COLOR_BLUE+1)
#define OSDSETUP_ENTRY_ICON_COLOR_GREEN         (OSDSETUP_ENTRY_ICON_COLOR_RED+1)
#endif


#define OSDSETUP_VALUE_COLOR_TOP_BANNER1         0x0000FF // need mix enable
#define OSDSETUP_VALUE_COLOR_TOP_BANNER_TEXT1    0xFFFFFF // need mix enable
#define OSDSETUP_VALUE_CENTER_COLOR_BG1          0x00AAFF // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER1      0x0000FF // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER_TEXT1 0xFFFFFF // need mix enable

#define OSDSETUP_VALUE_COLOR_TOP_BANNER2         0xF5BB30 // need mix enable
#define OSDSETUP_VALUE_COLOR_TOP_BANNER_TEXT2    0xA73C24 // need mix enable
#define OSDSETUP_VALUE_CENTER_COLOR_BG2          0xC3DFBD // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER2      0x5BBEFD // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER_TEXT2 0xFFFFFF // need mix enable

// UI Style 3
#define OSDSETUP_VALUE_COLOR_TOP_BANNER3         0xE7D074 // need mix enable
#define OSDSETUP_VALUE_COLOR_TOP_BANNER_TEXT3    0x395593 // need mix enable
#define OSDSETUP_VALUE_CENTER_COLOR_BG3          0x93A8D8 // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER3      0xC694F0 // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER_TEXT3 0xFFFFFF // need mix enable


#define OSDSETUP_VALUE_COLOR_TOP_BANNER4         0x34B3E0 // need mix enable
#define OSDSETUP_VALUE_COLOR_TOP_BANNER_TEXT4    0x424688 // need mix enable
#define OSDSETUP_VALUE_CENTER_COLOR_BG4          0xF1EC8F // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER4      0xF4A695 // need mix enable
#define OSDSETUP_VALUE_COLOR_BOTTOM_BANNER_TEXT4 0xFFFFFF // need mix enable


#define OSDMENU_VALUE_MENU_COLOR_BRIGHT                 0xFFFFFF
#define OSDMENU_VALUE_MENU_COLOR_DARK                   0x202020
#define OSDMENU_VALUE_MENU_COLOR_CENTER                 0xC0C0C0
#define OSDMENU_VALUE_TEXT_COLOR_NORMAL                 0x202020 
#define OSDMENU_VALUE_TEXT_COLOR_DISABLE                0x888888 
#define OSDMENU_VALUE_DESC_TEXT_COLOR                   0xE8E8E8
#define OSDMENU_VALUE_ITEM_COLOR_SELECT                 0x909090 // dark gray
#define OSDMENU_VALUE_ITEM_COLOR_HIGHLIGHT              0xEEED06 // yellow  

#define OSDSETUP_VALUE_COLOR_WHITE              0xFEFEFE // white 
#define OSDSETUP_VALUE_COLOR_ORANGE             0xAA0000 // need mix enable
#define OSDSETUP_VALUE_FRAME_BRIGHT             0xFFFFFF
#define OSDSETUP_VALUE_FRAME_DARK               0x888888
#define OSDSETUP_VALUE_FRAME_CENTER             0xC0C0C0
#define OSDSETUP_VALUE_HELP_COLOR_BG            0x0000C0 // need mix enable
#define OSDSETUP_VALUE_ICON_COLOR_BG            0x016FFF // need mix enable
#define OSDSETUP_VALUE_SPEAKER_HIGHLIGHT        0xFF0290 // orange

#define OSDSETUP_VALUE_ICON_RECT                0xCCCCFF
#define OSDSETUP_VALUE_ICON_NORMAL              0xC0C0C0 // gray
#define OSDSETUP_VALUE_ICON_OVER                0xEEED06 // yellow
#define OSDSETUP_VALUE_ICON_DOWN                0x868686 // dark gray






#ifdef REMOVE_SETUP_ICON
#define OSDSETUP_VALUE_ICON_ORANGE              0xFFA928
#define OSDSETUP_VALUE_ICON_BLUE                0x88D6F6
#define OSDSETUP_VALUE_ICON_RED                 0xEA3538
#define OSDSETUP_VALUE_ICON_GREEN               0x4CA151
#endif

#define MENU_BORDER_THICKNESS   2

#ifdef PRESTOP_BEFORE_SETUP_AND_PROGRAM
extern BYTE __bPreCountStop;
#endif

#endif  //__SETUP_H__
