//**************************************************************************
//         Copyright (c) 2004, Cheertek Inc . All rights reserved.
//         D300, all right reserved.

//      Product : WinDVD Firmware

//      Date    : 2004.5.31
//      Author  : Cheertek (D300 CoCo Chiang)
//      Purpose : Display mode UI
//      Sources : OSDDSPLY.c/OSDDSPLY.h
//***************************************************************************
#ifndef __OSDDSPLY_H__
#define __OSDDSPLY_H__

//***************************************************************************
//Open/Close the features of Display mode 
//***************************************************************************

//Open this define to support entering "Time" mode after "OSDDSPLY_LD_ENTER_SPECIAL_TIME_MODE" seconds.
#define OSDDSPLY_SUPPORT_ENTER_TIME_MODE

//Open this define to support show current display mode before changing to next display mode in time mode.
#define OSDDSPLY_SUPPORT_SHOW_CURRENT_DISPLAY_BEFORE_SWITCH

//Open this define to support show remain time
//#define OSDDSPLY_SUPPORT_SHOW_REMAIN_TIME_FOR_DIVX

//Open this define to support the vertical starting position if from top of the icon.
#define OSDDSPLY_NAVIGATOR_SUBMENU_START_FROM_ICON_TOP

//***************************************************************************
//Tune the setting of Display mode
//***************************************************************************

//Define the time to clear the Line Display and show "Time" only
#define  OSDDSPLY_LD_ENTER_SPECIAL_TIME_MODE        COUNT_5_SEC

//Define the value of the arc for background
#define OSDDSPLY_BACKGROUND_ARC_VALUE               13 //Arc can be 13, 15, 17, 19, 21, 23, 25.

//Define the value of the arc for background
#define OSDDSPLY_BACKGROUND_OUTER_ARC_VALUE         19 //Arc can be 13, 15, 17, 19, 21, 23, 25.

//define the pixels between the outer and inner arc of the background
#define OSDDSPLY_BACKGROUND_OUTER_INNER_ARC_PIXEL   (OSDDSPLY_BACKGROUND_OUTER_ARC_VALUE-OSDDSPLY_BACKGROUND_ARC_VALUE)

//define the mix ratio of the background for one-line display
#define OSDDSPLY_LD_MIX_RATIO_BACKGROUND        GDI_GENERAL_MIX_RATIO

//define the distance between the time "title" and time
#define OSDDSPLY_LD_DISTANCE_TIME_TITLE_TIME    4

//***************************************************************************
//Common settings for Display mode UI
//***************************************************************************

//define the maximum length for the string buffer.
#define OSDDSPLY_STRING_LENGTH                  30
#define OSDDSPLY_STRING_HEIGHT			26		

//CoCo1.0, add independent Navigator UI
#ifdef SUPPORT_INDEPENDENT_NAVIGATOR
#define OSDDSPLY_DVD_DISPLAY_NUM                5
#else
#define OSDDSPLY_DVD_DISPLAY_NUM                6
#endif
#define OSDDSPLY_VCD_DISPLAY_NUM                4
#define OSDDSPLY_JPEG_DISPLAY_NUM               2
#define OSDDSPLY_CDROM_AV_DISPLAY_NUM           1
#define OSDDSPLY_CDROM_AUDIO_DISPLAY_NUM        1
#ifdef OSDDSPLY_SUPPORT_SHOW_REMAIN_TIME_FOR_DIVX
#define OSDDSPLY_CDROM_DIVX_DISPLAY_NUM         3
#else
#define OSDDSPLY_CDROM_DIVX_DISPLAY_NUM         2
#endif //OSDDSPLY_SUPPORT_SHOW_REMAIN_TIME_FOR_DIVX

#define OSDDSPLY_MODE_NONE                      0
//DVD Display mode group
#define OSDDSPLY_MODE_DVD_TITLE_ELAPSED         (OSDDSPLY_MODE_NONE+1)
#define OSDDSPLY_MODE_DVD_TITLE_REMAIN          (OSDDSPLY_MODE_NONE+2)
#define OSDDSPLY_MODE_DVD_CHAPTER_ELAPSED       (OSDDSPLY_MODE_NONE+3)
#define OSDDSPLY_MODE_DVD_CHAPTER_REMAIN        (OSDDSPLY_MODE_NONE+4)
#define OSDDSPLY_MODE_DVD_VIRTUAL_PANEL         (OSDDSPLY_MODE_NONE+5)
#define OSDDSPLY_MODE_DVD_NAVIGATOR             (OSDDSPLY_MODE_NONE+6)
//VCD Display mode group
#define OSDDSPLY_MODE_VCD_SINGLE_ELAPSED        (OSDDSPLY_MODE_NONE+7)
#define OSDDSPLY_MODE_VCD_SINGLE_REMAIN         (OSDDSPLY_MODE_NONE+8)
#define OSDDSPLY_MODE_VCD_TOTAL_ELAPSED         (OSDDSPLY_MODE_NONE+9)
#define OSDDSPLY_MODE_VCD_TOTAL_REMAIN          (OSDDSPLY_MODE_NONE+10)
//JPEG Display mode group
#define OSDDSPLY_MODE_JPEG_LD                   (OSDDSPLY_MODE_NONE+11)
#define OSDDSPLY_MODE_JPEG_VIRTUAL_PANEL        (OSDDSPLY_MODE_NONE+12)
#define OSDDSPLY_MODE_CDROM_AUDIO               (OSDDSPLY_MODE_NONE+13)
#define OSDDSPLY_MODE_CDROM_MOTION_ELAPSED      (OSDDSPLY_MODE_NONE+14)
#define OSDDSPLY_MODE_CDROM_MOTION_REMAIN       (OSDDSPLY_MODE_NONE+15)
#define OSDDSPLY_MODE_DIVX_VIRTUAL_PANEL        (OSDDSPLY_MODE_NONE+16)   

//Parameter for update region/background
#define OSDDSPLY_DRAW_REGION                    0
#define OSDDSPLY_CLEAR_REGION                   1

//define the type of the background.
#define OSDDSPLY_BACKGROUND_NONE                0
#define OSDDSPLY_BACKGROUND_LD_GENERAL          1
#define OSDDSPLY_BACKGROUND_LD_TIME             2
#define OSDDSPLY_BACKGROUND_VP_DVD              3
#define OSDDSPLY_BACKGROUND_VP_JPEG             4
#define OSDDSPLY_BACKGROUND_VP_DIVX             5
#define OSDDSPLY_BACKGROUND_NAVIGATOR           6

//define the item/info. update
#define OSDDSPLY_UPDATE_ITEM                    0x01
#define OSDDSPLY_UPDATE_INFO                    0x02

/////////////////////////////////////////////////////////////////////////////
#define OSDDSPLY_MODE_LD						0
#define OSDDSPLY_MODE_VP						1


/////////////////////////////////////////////////////////////////////////////
typedef struct tagDisplayMode
{
    BYTE bDisplayModeID;
    BYTE bBackgroundType;    
} DISPLAYMODE, *PDISPLAYMODE;


//***************************************************************************
//One-line Display
//***************************************************************************
//define the region for one-line display
#define OSDDSPLY_REGION_LD_START                0
#define OSDDSPLY_REGION_LD_TITLE                OSDDSPLY_REGION_LD_START
#define OSDDSPLY_REGION_LD_CHAPTER              (OSDDSPLY_REGION_LD_START+1)
#define OSDDSPLY_REGION_LD_TIME                 (OSDDSPLY_REGION_LD_START+2)
#define OSDDSPLY_REGION_LD_PROGRAM_STATUS       (OSDDSPLY_REGION_LD_START+3)
#define OSDDSPLY_REGION_TIME_LD_TIME            (OSDDSPLY_REGION_LD_START+4)
#define OSDDSPLY_REGION_LD_FILE_NAME            (OSDDSPLY_REGION_LD_START+5)
#define OSDDSPLY_REGION_LD_FILE_NUM             (OSDDSPLY_REGION_LD_START+6)
#define OSDDSPLY_REGION_LD_CDROM_TIME           (OSDDSPLY_REGION_LD_START+7)
#define OSDDSPLY_REGION_LD_MENU					(OSDDSPLY_REGION_LD_START+8)


//define the regions for one-line display
#define OSDDSPLY_LD_REGION_TITL                         0
#define OSDDSPLY_LD_REGION_CHAPTER                      1
#define OSDDSPLY_LD_REGION_TIME                         2
#define OSDDSPLY_LD_REGION_STATUS                       3
#define OSDDSPLY_LD_REGION_ALL                          0xFF

//define the starting entry for color palette
#ifdef USE_4B_MODE_OSD
#define OSDDSPLY_LD_PALETTE_ENTRY_START                 (GDI_ND_PALETTE_INDEX_START+GDI_ND_PALETTE_NUM)    
#else
#define OSDDSPLY_LD_PALETTE_ENTRY_START                 GDI_GENERAL_UI_PALETTE_INDEX_START
#endif //USE_4B_MODE_OSD

//define the palette entry
#ifdef USE_4B_MODE_OSD
#define OSDDSPLY_LD_PALETTE_ENTRY_GENERAL_BACKGROUND                OSDDSPLY_LD_PALETTE_ENTRY_START
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM                 (OSDDSPLY_LD_PALETTE_ENTRY_START+1)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO                 (OSDDSPLY_LD_PALETTE_ENTRY_START+2)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_PROGRAM_STATUS             (OSDDSPLY_LD_PALETTE_ENTRY_START+3)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_ITEM               OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_INFO               OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TIME_INFO                  OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_ITEM_TEXT        OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_INFO             OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_ITEM_TEXT         OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_INFO              OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_MENU						OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM
#define OSDDSPLY_LD_PALETTE_ENTRY_END                               OSDDSPLY_LD_PALETTE_ENTRY_REGION_PROGRAM_STATUS
#else
#define OSDDSPLY_LD_PALETTE_ENTRY_GENERAL_BACKGROUND                OSDDSPLY_LD_PALETTE_ENTRY_START
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM                 (OSDDSPLY_LD_PALETTE_ENTRY_START+1)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO                 (OSDDSPLY_LD_PALETTE_ENTRY_START+2)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_ITEM               (OSDDSPLY_LD_PALETTE_ENTRY_START+3)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_INFO               (OSDDSPLY_LD_PALETTE_ENTRY_START+4)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_TIME_INFO                  (OSDDSPLY_LD_PALETTE_ENTRY_START+5)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_PROGRAM_STATUS             (OSDDSPLY_LD_PALETTE_ENTRY_START+6)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_ITEM_TEXT        (OSDDSPLY_LD_PALETTE_ENTRY_START+7)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_INFO             (OSDDSPLY_LD_PALETTE_ENTRY_START+8)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_ITEM_TEXT         (OSDDSPLY_LD_PALETTE_ENTRY_START+9)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_INFO              (OSDDSPLY_LD_PALETTE_ENTRY_START+10)
#define OSDDSPLY_LD_PALETTE_ENTRY_GENERAL_BACKGROUND_FRAME          (OSDDSPLY_LD_PALETTE_ENTRY_START+11)
#define OSDDSPLY_LD_PALETTE_ENTRY_REGION_MENU						(OSDDSPLY_LD_PALETTE_ENTRY_START+12)
#define OSDDSPLY_LD_PALETTE_ENTRY_END                               OSDDSPLY_LD_PALETTE_ENTRY_REGION_MENU
#endif 

//define the palette color
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_1              0x606060
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_2              0xB0DBD7     
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_3              0x8383FC     
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_4              0xFCFF42          
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_1               0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_2               0x192BB1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_3               0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_4               0xE16D01
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_ITEM_1             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_ITEM_2             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_ITEM_3             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_ITEM_4             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_PROGRAM_STATUS_1           0xFFD900
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_PROGRAM_STATUS_2           0xFFC8C8//0xC60010
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_PROGRAM_STATUS_3           0xFFC8C8//0xC60010
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_PROGRAM_STATUS_4           0x1601E0
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_ITEM_TEXT_1      OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_ITEM_TEXT_2      OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_ITEM_TEXT_3      OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_ITEM_TEXT_4      OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_ITEM_TEXT_1       OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_ITEM_TEXT_2       OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_ITEM_TEXT_3       OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_ITEM_TEXT_4       OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_1               0xFFCC00
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_2               0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_3               0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_4               0x404111
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_INFO_1             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_INFO_2             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_INFO_3             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_CHAPTER_INFO_4             OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TIME_INFO_1                OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TIME_INFO_2                OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TIME_INFO_3                OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_TIME_INFO_4                OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_INFO_1           OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_INFO_2           OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_INFO_3           OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NAME_INFO_4           OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_INFO_1            OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_INFO_2            OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_INFO_3            OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_FILE_NUM_INFO_4            OSDDSPLY_LD_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_MENU_1						0xFFCC00
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_MENU_2						0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_MENU_3						0xFFFFFF
#define OSDDSPLY_LD_PALETTE_COLOR_REGION_MENU_4						0x404111
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_1        0x404040
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_2        0x404111
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_3        0x999FAB
#define OSDDSPLY_LD_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_4        0x404111


//define the vertical distance between the normal display and line display.
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_ND_LD_DISTANCE_V                       0
#else
#define OSDDSPLY_ND_LD_DISTANCE_V                       8
#endif //SUPPORT_SIMPLE_DISPLAY_MODE

//define the starting position and the size of the one-line Display
#define OSDDSPLY_LD_START_H                             8
#define OSDDSPLY_LD_START_V                             (OSDND_UPPER_BACKGROUND_BOTTOM+OSDDSPLY_ND_LD_DISTANCE_V+1)//42
#define OSDDSPLY_LD_WIDTH                               600

#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_LD_HEIGHT                              26
#else
#define OSDDSPLY_LD_HEIGHT                              30
#endif //SUPPORT_SIMPLE_DISPLAY_MODE

//define the starting position and the size of the "TIME" one-line Display
#define OSDDSPLY_LD_TIME_START_H                        480
#define OSDDSPLY_LD_TIME_START_V                        (OSDND_UPPER_BACKGROUND_BOTTOM+OSDDSPLY_ND_LD_DISTANCE_V+1)//42
#define OSDDSPLY_LD_TIME_WIDTH                          112
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_LD_TIME_HEIGHT                         26
#else
#define OSDDSPLY_LD_TIME_HEIGHT                         30
#endif //SUPPORT_SIMPLE_DISPLAY_MODE

//define the distance between title and chapter
#define OSDDSPLY_LD_TIME_DISTANCE_START                 8

//Define the position to show time for "TIME" one-line display
#define OSDDSPLY_LD_TIME_SHOW_TIME_START_H              (OSDDSPLY_LD_TIME_START_H+OSDDSPLY_LD_TIME_DISTANCE_START)             

//The "title" region for DVD
#define OSDDSPLY_LD_DISTANCE_REGION_START_TITLE         16
#define OSDDSPLY_LD_REGION_TITLE_START_H                (OSDDSPLY_LD_START_H+OSDDSPLY_LD_DISTANCE_REGION_START_TITLE)
#define OSDDSPLY_LD_REGION_TITLE_WIDTH                  112
#define OSDDSPLY_LD_REGION_TITLE_ITEM_COLOR             OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_ITEM
#define OSDDSPLY_LD_REGION_TITLE_INFO_COLOR             OSDDSPLY_LD_PALETTE_ENTRY_REGION_TITLE_INFO

//define the distance between title and chapter
#define OSDDSPLY_LD_DISTANCE_REGION_TITLE_CHAPTER       0

//The "Chapter" region for DVD
#define OSDDSPLY_LD_REGION_CHAPTER_START_H              (OSDDSPLY_LD_REGION_TITLE_START_H+OSDDSPLY_LD_REGION_TITLE_WIDTH+OSDDSPLY_LD_DISTANCE_REGION_TITLE_CHAPTER)
#define OSDDSPLY_LD_REGION_CHAPTER_WIDTH                112
#define OSDDSPLY_LD_REGION_CHAPTER_ITEM_COLOR           OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_ITEM
#define OSDDSPLY_LD_REGION_CHAPTER_INFO_COLOR           OSDDSPLY_LD_PALETTE_ENTRY_REGION_CHAPTER_INFO

//"Menu" Region: display the Title Menu. A special "title+chapter" region (for DVD menu, title menu)
#define OSDDSPLY_LD_REGION_MENU_START_H					OSDDSPLY_LD_REGION_TITLE_START_H
#define OSDDSPLY_LD_REGION_MENU_WIDTH                   (OSDDSPLY_LD_REGION_TITLE_WIDTH+OSDDSPLY_LD_DISTANCE_REGION_TITLE_CHAPTER+OSDDSPLY_LD_REGION_CHAPTER_WIDTH)
#define OSDDSPLY_LD_REGION_MENU_COLOR                   OSDDSPLY_LD_PALETTE_ENTRY_REGION_MENU

//define the distance between chapter and time
#define OSDDSPLY_LD_DISTANCE_REGION_CHAPTER_TIME        0

//The "time" region
#define OSDDSPLY_LD_REGION_TIME_START_H                 (OSDDSPLY_LD_REGION_CHAPTER_START_H+OSDDSPLY_LD_REGION_CHAPTER_WIDTH+OSDDSPLY_LD_DISTANCE_REGION_CHAPTER_TIME)
#define OSDDSPLY_LD_REGION_TIME_WIDTH                   304
#define OSDDSPLY_LD_REGION_TIME_INFO_COLOR              OSDDSPLY_LD_PALETTE_ENTRY_REGION_TIME_INFO

//define the distance between status and end
#define OSDDSPLY_LD_DISTANCE_REGION_PROGRAM_STATUS_END  16

//The "status" region
#define OSDDSPLY_LD_REGION_PROGRAM_STATUS_WIDTH         32
#define OSDDSPLY_LD_REGION_PROGRAM_STATUS_START_H       (OSDDSPLY_LD_START_H+OSDDSPLY_LD_WIDTH-OSDDSPLY_LD_DISTANCE_REGION_PROGRAM_STATUS_END-OSDDSPLY_LD_REGION_PROGRAM_STATUS_WIDTH)
#define OSDDSPLY_LD_REGION_PROGRAM_STATUS_COLOR         OSDDSPLY_LD_PALETTE_ENTRY_REGION_PROGRAM_STATUS

//define the distance between start and file name
#define OSDDSPLY_LD_DISTANCE_REGION_START_FILE_NAME     16

//Define the max. DIR and file name in the File name region
#define OSDDSPLY_LD_REGION_FILE_DIR_NAME_MAX_WIDTH      288 //300

//The "FILE NAME" region
#define OSDDSPLY_LD_REGION_FILE_NAME_START_H            (OSDDSPLY_LD_START_H+OSDDSPLY_LD_DISTANCE_REGION_START_FILE_NAME)
#define OSDDSPLY_LD_REGION_FILE_NAME_WIDTH              OSDDSPLY_LD_REGION_FILE_DIR_NAME_MAX_WIDTH
#define OSDDSPLY_LD_REGION_FILE_NAME_ITEM_TEXT_COLOR    OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_ITEM_TEXT
#define OSDDSPLY_LD_REGION_FILE_NAME_INFO_COLOR         OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NAME_INFO

//define the distance between "FILE NAME" and "FILE NUM"
#define OSDDSPLY_LD_DISTANCE_REGION_FILE_NAME_FILE_NUM  0//8

//The "FILE NAME" region
#define OSDDSPLY_LD_REGION_FILE_NUM_START_H             (OSDDSPLY_LD_REGION_FILE_NAME_START_H+OSDDSPLY_LD_REGION_FILE_DIR_NAME_MAX_WIDTH+OSDDSPLY_LD_DISTANCE_REGION_FILE_NAME_FILE_NUM)
#define OSDDSPLY_LD_REGION_FILE_NUM_WIDTH               144//120
#define OSDDSPLY_LD_REGION_FILE_NUM_ITEM_TEXT_COLOR     OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_ITEM_TEXT
#define OSDDSPLY_LD_REGION_FILE_NUM_INFO_COLOR          OSDDSPLY_LD_PALETTE_ENTRY_REGION_FILE_NUM_INFO

#define OSDDSPLY_LD_DISTANCE_REGION_FILENUM_TIME        0//8

//The "time" region
#define OSDDSPLY_LD_REGION_CDROM_TIME_START_H           (OSDDSPLY_LD_REGION_FILE_NUM_START_H+OSDDSPLY_LD_REGION_FILE_NUM_WIDTH+OSDDSPLY_LD_DISTANCE_REGION_FILENUM_TIME)
#define OSDDSPLY_LD_REGION_CDROM_TIME_WIDTH             (OSDDSPLY_LD_REGION_PROGRAM_STATUS_START_H-OSDDSPLY_LD_REGION_CDROM_TIME_START_H-1)
#define OSDDSPLY_LD_REGION_CDROM_TIME_COLOR             OSDDSPLY_LD_PALETTE_ENTRY_REGION_TIME_INFO

//***************************************************************************
//Virtual Panel
//***************************************************************************

//define the region for virtual panel.
#define OSDDSPLY_REGION_VP_START                0
#define OSDDSPLY_REGION_VP_TITLE                OSDDSPLY_REGION_VP_START
#define OSDDSPLY_REGION_VP_CHAPTER              (OSDDSPLY_REGION_VP_START+1)
#define OSDDSPLY_REGION_VP_SUBTITLE             (OSDDSPLY_REGION_VP_START+2)
#define OSDDSPLY_REGION_VP_AST                  (OSDDSPLY_REGION_VP_START+3)
#define OSDDSPLY_REGION_VP_TIME                 (OSDDSPLY_REGION_VP_START+4)
#define OSDDSPLY_REGION_VP_PROGRAM_STATUS       (OSDDSPLY_REGION_VP_START+5)    
#define OSDDSPLY_REGION_VP_REPEAT_STATUS        (OSDDSPLY_REGION_VP_START+6)
#define OSDDSPLY_REGION_VP_PLAY_STATUS          (OSDDSPLY_REGION_VP_START+7)
#define OSDDSPLY_REGION_VP_TV                   (OSDDSPLY_REGION_VP_START+8)
#define OSDDSPLY_REGION_VP_ANGLE                (OSDDSPLY_REGION_VP_START+9)
#define OSDDSPLY_REGION_VP_MENU                 (OSDDSPLY_REGION_VP_START+10)
#define OSDDSPLY_REGION_VP_FILE_NAME            (OSDDSPLY_REGION_VP_START+11)
#define OSDDSPLY_REGION_VP_FILE_NUM             (OSDDSPLY_REGION_VP_START+12)
#define OSDDSPLY_REGION_VP_RESOLUTION           (OSDDSPLY_REGION_VP_START+13)
#define OSDDSPLY_REGION_VP_DATE                 (OSDDSPLY_REGION_VP_START+14)
#define OSDDSPLY_REGION_VP_MOTION_FILE_NAME     (OSDDSPLY_REGION_VP_START+15)
#define OSDDSPLY_REGION_VP_MOTION_FILE_NUM      (OSDDSPLY_REGION_VP_START+16)
#define OSDDSPLY_REGION_VP_MOTION_TIME          (OSDDSPLY_REGION_VP_START+17)

//define the starting entry for color palette
#ifdef USE_4B_MODE_OSD
#define OSDDSPLY_VP_PALETTE_ENTRY_START                 (GDI_ND_PALETTE_INDEX_START+GDI_ND_PALETTE_NUM)    
#else
#define OSDDSPLY_VP_PALETTE_ENTRY_START                 (OSDDSPLY_LD_PALETTE_ENTRY_END+1)
#endif //USE_4B_MODE_OSD

//define the palette entry
#ifdef USE_4B_MODE_OSD
#define OSDDSPLY_VP_PALETTE_ENTRY_GENERAL_BACKGROUND                OSDDSPLY_VP_PALETTE_ENTRY_START
#define OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM                (OSDDSPLY_VP_PALETTE_ENTRY_START+1)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO                 (OSDDSPLY_VP_PALETTE_ENTRY_START+2)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_PROGRAM_STATUS             (OSDDSPLY_VP_PALETTE_ENTRY_START+3)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_ITEM               OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_INFO               OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TIME                       OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_PLAY_STATUS                OSDDSPLY_VP_PALETTE_ENTRY_REGION_PROGRAM_STATUS
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_REPEAT_STATUS              OSDDSPLY_VP_PALETTE_ENTRY_REGION_PROGRAM_STATUS
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_ITEM              OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_INFO              OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_ITEM                   OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_INFO                   OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_ITEM                    OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_INFO                    OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_ITEM                 OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_INFO                 OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_MENU                       OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_ITEM             OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_INFO             OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_ITEM              OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_INFO              OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_ITEM            OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_INFO            OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_ITEM                  OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_INFO                  OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO
#define OSDDSPLY_VP_PALETTE_ENTRY_END                               OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_INFO
#else
#define OSDDSPLY_VP_PALETTE_ENTRY_GENERAL_BACKGROUND                OSDDSPLY_VP_PALETTE_ENTRY_START
#define OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM                (OSDDSPLY_VP_PALETTE_ENTRY_START+1)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO                 (OSDDSPLY_VP_PALETTE_ENTRY_START+2)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_ITEM               (OSDDSPLY_VP_PALETTE_ENTRY_START+3)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_INFO               (OSDDSPLY_VP_PALETTE_ENTRY_START+4)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TIME                       (OSDDSPLY_VP_PALETTE_ENTRY_START+5)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_PROGRAM_STATUS             (OSDDSPLY_VP_PALETTE_ENTRY_START+6)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_PLAY_STATUS                (OSDDSPLY_VP_PALETTE_ENTRY_START+7)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_REPEAT_STATUS              (OSDDSPLY_VP_PALETTE_ENTRY_START+8)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_ITEM              (OSDDSPLY_VP_PALETTE_ENTRY_START+9)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_INFO              (OSDDSPLY_VP_PALETTE_ENTRY_START+10)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_ITEM                   (OSDDSPLY_VP_PALETTE_ENTRY_START+11)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_INFO                   (OSDDSPLY_VP_PALETTE_ENTRY_START+12)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_ITEM                    (OSDDSPLY_VP_PALETTE_ENTRY_START+13)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_INFO                    (OSDDSPLY_VP_PALETTE_ENTRY_START+14)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_ITEM                 (OSDDSPLY_VP_PALETTE_ENTRY_START+15)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_INFO                 (OSDDSPLY_VP_PALETTE_ENTRY_START+16)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_MENU                       (OSDDSPLY_VP_PALETTE_ENTRY_START+17)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_ITEM             (OSDDSPLY_VP_PALETTE_ENTRY_START+18)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_INFO             (OSDDSPLY_VP_PALETTE_ENTRY_START+19)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_ITEM              (OSDDSPLY_VP_PALETTE_ENTRY_START+20)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_INFO              (OSDDSPLY_VP_PALETTE_ENTRY_START+21)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_ITEM            (OSDDSPLY_VP_PALETTE_ENTRY_START+22)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_INFO            (OSDDSPLY_VP_PALETTE_ENTRY_START+23)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_ITEM                  (OSDDSPLY_VP_PALETTE_ENTRY_START+24)
#define OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_INFO                  (OSDDSPLY_VP_PALETTE_ENTRY_START+25)
#define OSDDSPLY_VP_PALETTE_ENTRY_END                               OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_INFO
#endif //USE_4B_MODE_OSD

#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_1              0x606060     
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_2              0xB0DBD7
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_3              0x8383FC
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_4              0xFCFF42
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1               0xFFFFFF
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2               0x192BB1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3               0xFFFFFF
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4               0xE16D01
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_ITEM_1             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_ITEM_2             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_ITEM_3             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_ITEM_4             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_ITEM_1            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1         
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_ITEM_2            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2         
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_ITEM_3            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3         
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_ITEM_4            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4         
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_ITEM_1                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1    
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_ITEM_2                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2    
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_ITEM_3                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3    
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_ITEM_4                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4    
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_ITEM_1                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_ITEM_2                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_ITEM_3                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_ITEM_4                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_ITEM_1               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_ITEM_2               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_ITEM_3               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_ITEM_4               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_ITEM_1           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_ITEM_2           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_ITEM_3           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_ITEM_4           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_ITEM_1            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_ITEM_2            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_ITEM_3            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_ITEM_4            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_ITEM_1          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_ITEM_2          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_ITEM_3          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_ITEM_4          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_ITEM_1                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_ITEM_2                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_ITEM_3                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_ITEM_4                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_ITEM_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_1           0xFFD900
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_2           0xFFC8C8//0xC60010
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_3           0xFFC8C8//0xC60010
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_4           0x1601E0
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PLAY_STATUS_1              OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PLAY_STATUS_2              OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PLAY_STATUS_3              OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_PLAY_STATUS_4              OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_REPEAT_STATUS_1            OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_REPEAT_STATUS_2            OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_REPEAT_STATUS_3            OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_REPEAT_STATUS_4            OSDDSPLY_VP_PALETTE_COLOR_REGION_PROGRAM_STATUS_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1               0xFFCC00
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2               0xFFFFFF
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3               0xFFFFFF
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4               0x404111
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_INFO_1             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_INFO_2             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_INFO_3             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_CHAPTER_INFO_4             OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TIME_1                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TIME_2                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TIME_3                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TIME_4                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_INFO_1            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1           
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_INFO_2            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2           
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_INFO_3            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3           
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_SUBTITLE_INFO_4            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4           
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_INFO_1                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_INFO_2                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_INFO_3                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_AST_INFO_4                 OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_INFO_1                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1     
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_INFO_2                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2     
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_INFO_3                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3     
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_TV_INFO_4                  OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4     
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_INFO_1               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_INFO_2               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_INFO_3               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_ANGLE_INFO_4               OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_MENU_1                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_MENU_2                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_MENU_3                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_MENU_4                     OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_INFO_1           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_INFO_2           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_INFO_3           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NAME_INFO_4           OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_INFO_1            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_INFO_2            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_INFO_3            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_FILE_NUM_INFO_4            OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_INFO_1          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_INFO_2          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_INFO_3          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_RESOLUTION_INFO_4          OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_INFO_1                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_1
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_INFO_2                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_2
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_INFO_3                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_3
#define OSDDSPLY_VP_PALETTE_COLOR_REGION_DATE_INFO_4                OSDDSPLY_VP_PALETTE_COLOR_REGION_TITLE_INFO_4
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_1        0x404040
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_2        0x404111
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_3        0x999FAB
#define OSDDSPLY_VP_PALETTE_COLOR_GENERAL_BACKGROUND_FRAME_4        0x404111

//define the starting position and the size of the virtual panel.
#define OSDDSPLY_VP_START_H                                         OSDDSPLY_BACKGROUND_OUTER_INNER_ARC_PIXEL
#define OSDDSPLY_VP_START_V                                         (OSDND_UPPER_BACKGROUND_BOTTOM+OSDDSPLY_ND_LD_DISTANCE_V+1)//54
#define OSDDSPLY_VP_WIDTH                                           600

//define the height of each line.
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_LINE_0_HEIGHT                            26
#define OSDDSPLY_VP_REGION_LINE_1_HEIGHT                            26
#define OSDDSPLY_VP_REGION_LINE_2_HEIGHT                            26
#else
#define OSDDSPLY_VP_REGION_LINE_0_HEIGHT                            30
#define OSDDSPLY_VP_REGION_LINE_1_HEIGHT                            30
#define OSDDSPLY_VP_REGION_LINE_2_HEIGHT                            30
#endif //SUPPORT_SIMPLE_DISPLAY_MODE

//define the distance between each line
#define OSDDSPLY_VP_DISTANCE_LINE_0_1                               0//5
#define OSDDSPLY_VP_DISTANCE_LINE_1_2                               0//5

//define the vertical string position for each line
#define OSDDSPLY_VP_REGION_LINE_0_START_V                           OSDDSPLY_VP_START_V
#define OSDDSPLY_VP_REGION_LINE_1_START_V                           (OSDDSPLY_VP_REGION_LINE_0_START_V+OSDDSPLY_VP_REGION_LINE_0_HEIGHT+OSDDSPLY_VP_DISTANCE_LINE_0_1)
#define OSDDSPLY_VP_REGION_LINE_2_START_V                           (OSDDSPLY_VP_REGION_LINE_1_START_V+OSDDSPLY_VP_REGION_LINE_1_HEIGHT+OSDDSPLY_VP_DISTANCE_LINE_1_2)

//define the height of the virtual panel
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_DVD_HEIGHT                                      (OSDDSPLY_VP_REGION_LINE_0_HEIGHT)
#define OSDDSPLY_VP_JPEG_HEIGHT                                     (OSDDSPLY_VP_REGION_LINE_0_HEIGHT)
#else
#define OSDDSPLY_VP_DVD_HEIGHT                                      (OSDDSPLY_VP_REGION_LINE_0_HEIGHT+OSDDSPLY_VP_DISTANCE_LINE_0_1+OSDDSPLY_VP_REGION_LINE_1_HEIGHT+OSDDSPLY_VP_DISTANCE_LINE_1_2+OSDDSPLY_VP_REGION_LINE_2_HEIGHT)
#define OSDDSPLY_VP_JPEG_HEIGHT                                     (OSDDSPLY_VP_REGION_LINE_0_HEIGHT+OSDDSPLY_VP_DISTANCE_LINE_0_1+OSDDSPLY_VP_REGION_LINE_1_HEIGHT)
#endif //SUPPORT_SIMPLE_DISPLAY_MODE

//"Title" Region: display the title for DVD
#define OSDDSPLY_VP_REGION_TITLE_START_H                            (OSDDSPLY_VP_START_H+12)
#define OSDDSPLY_VP_REGION_TITLE_START_V                            OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_TITLE_WIDTH                              152
#define OSDDSPLY_VP_REGION_TITLE_HEIGHT                             OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_TITLE_ITEM_COLOR                         OSDDSPLY_VP_PALETTE_ENTTRY_REGION_TITLE_ITEM
#define OSDDSPLY_VP_REGION_TITLE_INFO_COLOR                         OSDDSPLY_VP_PALETTE_ENTRY_REGION_TITLE_INFO

//define the distance between "title" and "chapter" region.
#define OSDDSPLY_VP_DISTANCE_REGION_TITLE_CHAPTER                   0

//"Chapter" Region: display the chapter for DVD
#define OSDDSPLY_VP_REGION_CHAPTER_START_H                          (OSDDSPLY_VP_REGION_TITLE_START_H+OSDDSPLY_VP_REGION_TITLE_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_TITLE_CHAPTER)                    
#define OSDDSPLY_VP_REGION_CHAPTER_START_V                          OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_CHAPTER_WIDTH                            184
#define OSDDSPLY_VP_REGION_CHAPTER_HEIGHT                           OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_CHAPTER_ITEM_COLOR                       OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_ITEM
#define OSDDSPLY_VP_REGION_CHAPTER_INFO_COLOR                       OSDDSPLY_VP_PALETTE_ENTRY_REGION_CHAPTER_INFO

//"Menu" Region: display the Title Menu. A special "title+chapter" region (for DVD menu, title menu)
#define OSDDSPLY_VP_REGION_MENU_START_H                             OSDDSPLY_VP_REGION_TITLE_START_H
#define OSDDSPLY_VP_REGION_MENU_START_V                             OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_MENU_WIDTH                               (OSDDSPLY_VP_REGION_TITLE_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_TITLE_CHAPTER+OSDDSPLY_VP_REGION_CHAPTER_WIDTH)
#define OSDDSPLY_VP_REGION_MENU_HEIGHT                              OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_MENU_COLOR                               OSDDSPLY_VP_PALETTE_ENTRY_REGION_MENU

//define the distance between "chapter" and "time" region.
#define OSDDSPLY_VP_DISTANCE_REGION_CHAPTER_TIME                    8

//"Time" Region: display the time
#define OSDDSPLY_VP_REGION_TIME_START_H                             (OSDDSPLY_VP_REGION_CHAPTER_START_H+OSDDSPLY_VP_REGION_CHAPTER_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_CHAPTER_TIME)
#define OSDDSPLY_VP_REGION_TIME_START_V                             OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_TIME_WIDTH                               128
#define OSDDSPLY_VP_REGION_TIME_HEIGHT                              OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_TIME_COLOR                               OSDDSPLY_VP_PALETTE_ENTRY_REGION_TIME

//define the distance between end and "play status" region.
#define OSDDSPLY_VP_DISTANCE_REGION_STATUS_END                      12

//define the distance betwwen each status
#define OSDDSPLY_VP_DISTANCE_STATUS_STATUS_H                        4

//"Play Status" Region: display playing status.
#define OSDDSPLY_VP_REGION_PLAY_STATUS_WIDTH                        32
#define OSDDSPLY_VP_REGION_PLAY_STATUS_START_H                      (OSDDSPLY_VP_START_H+OSDDSPLY_VP_WIDTH-OSDDSPLY_VP_DISTANCE_REGION_STATUS_END-OSDDSPLY_VP_REGION_PLAY_STATUS_WIDTH)
#define OSDDSPLY_VP_REGION_PLAY_STATUS_START_V                      OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_PLAY_STATUS_HEIGHT                       OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_PLAY_STATUS_COLOR                        OSDDSPLY_VP_PALETTE_ENTRY_REGION_PLAY_STATUS

//"Repeat Status" Region: display playing status.
#define OSDDSPLY_VP_REGION_REPEAT_STATUS_WIDTH                      32
#define OSDDSPLY_VP_REGION_REPEAT_STATUS_START_H                    (OSDDSPLY_VP_REGION_PLAY_STATUS_START_H - OSDDSPLY_VP_REGION_REPEAT_STATUS_WIDTH-OSDDSPLY_VP_DISTANCE_STATUS_STATUS_H)
#define OSDDSPLY_VP_REGION_REPEAT_STATUS_START_V                    OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_REPEAT_STATUS_HEIGHT                     OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_REPEAT_STATUS_COLOR                      OSDDSPLY_VP_PALETTE_ENTRY_REGION_REPEAT_STATUS

//"Program Status" Region: display program status.
#define OSDDSPLY_VP_REGION_PROGRAM_STATUS_WIDTH                     32
#define OSDDSPLY_VP_REGION_PROGRAM_STATUS_START_H                   (OSDDSPLY_VP_REGION_REPEAT_STATUS_START_H - OSDDSPLY_VP_REGION_PROGRAM_STATUS_WIDTH-OSDDSPLY_VP_DISTANCE_STATUS_STATUS_H)
#define OSDDSPLY_VP_REGION_PROGRAM_STATUS_START_V                   OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_PROGRAM_STATUS_HEIGHT                    OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_PROGRAM_STATUS_COLOR                     OSDDSPLY_VP_PALETTE_ENTRY_REGION_PROGRAM_STATUS

//"Subtitle" Region: display subtitle for DVD
#define OSDDSPLY_VP_REGION_SUBTITLE_START_H                         OSDDSPLY_VP_REGION_TITLE_START_H
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_SUBTITLE_START_V                         OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_SUBTITLE_WIDTH                           216
#else
#define OSDDSPLY_VP_REGION_SUBTITLE_START_V                         OSDDSPLY_VP_REGION_LINE_1_START_V
#define OSDDSPLY_VP_REGION_SUBTITLE_WIDTH                           288
#endif //SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_SUBTITLE_HEIGHT                          OSDDSPLY_VP_REGION_LINE_1_HEIGHT
#define OSDDSPLY_VP_REGION_SUBTITLE_ITEM_COLOR                      OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_ITEM
#define OSDDSPLY_VP_REGION_SUBTITLE_INFO_COLOR                      OSDDSPLY_VP_PALETTE_ENTRY_REGION_SUBTITLE_INFO

//define the distance between "Subtitle" and "AST" region
#define OSDDSPLY_VP_DISTANCE_REGION_SUBTITLE_AST                    0

//"AST" Region: display AST for DVD
#define OSDDSPLY_VP_REGION_AST_START_H                              (OSDDSPLY_VP_REGION_SUBTITLE_START_H+OSDDSPLY_VP_REGION_SUBTITLE_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_SUBTITLE_AST)
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_AST_START_V                              OSDDSPLY_VP_REGION_LINE_0_START_V
#else
#define OSDDSPLY_VP_REGION_AST_START_V                              OSDDSPLY_VP_REGION_LINE_1_START_V
#endif //SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_AST_WIDTH                                288//(OSDDSPLY_VP_START_H+OSDDSPLY_VP_WIDTH-OSDDSPLY_VP_REGION_AST_START_H-1)
#define OSDDSPLY_VP_REGION_AST_HEIGHT                               OSDDSPLY_VP_REGION_LINE_1_HEIGHT
#define OSDDSPLY_VP_REGION_AST_ITEM_COLOR                           OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_ITEM
#define OSDDSPLY_VP_REGION_AST_INFO_COLOR                           OSDDSPLY_VP_PALETTE_ENTRY_REGION_AST_INFO

//"TV" Region: display TV mode
#define OSDDSPLY_VP_REGION_TV_START_H                               OSDDSPLY_VP_REGION_TITLE_START_H
#define OSDDSPLY_VP_REGION_TV_START_V                               OSDDSPLY_VP_REGION_LINE_2_START_V
#define OSDDSPLY_VP_REGION_TV_WIDTH                                 288
#define OSDDSPLY_VP_REGION_TV_HEIGHT                                OSDDSPLY_VP_REGION_LINE_2_HEIGHT
#define OSDDSPLY_VP_REGION_TV_ITEM_COLOR                            OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_ITEM
#define OSDDSPLY_VP_REGION_TV_INFO_COLOR                            OSDDSPLY_VP_PALETTE_ENTRY_REGION_TV_INFO

//define the distance between TV amd angle
#define OSDDSPLY_VP_DISTANCE_REGION_TV_ANGLE                        8

//"Angle" Region: display angle
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_ANGLE_START_H                            (OSDDSPLY_VP_REGION_AST_START_H+OSDDSPLY_VP_REGION_AST_WIDTH)
#define OSDDSPLY_VP_REGION_ANGLE_START_V                            OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_ANGLE_WIDTH                              72
#else
#define OSDDSPLY_VP_REGION_ANGLE_START_H                            OSDDSPLY_VP_REGION_AST_START_H//(OSDDSPLY_VP_REGION_TV_START_H+OSDDSPLY_VP_REGION_TV_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_TV_ANGLE)
#define OSDDSPLY_VP_REGION_ANGLE_START_V                            OSDDSPLY_VP_REGION_LINE_2_START_V
#define OSDDSPLY_VP_REGION_ANGLE_WIDTH                              104
#endif //SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_ANGLE_HEIGHT                             OSDDSPLY_VP_REGION_LINE_2_HEIGHT
#define OSDDSPLY_VP_REGION_ANGLE_ITEM_COLOR                         OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_ITEM
#define OSDDSPLY_VP_REGION_ANGLE_INFO_COLOR                         OSDDSPLY_VP_PALETTE_ENTRY_REGION_ANGLE_INFO

//"File Name" Region: display JPEG file name
#define OSDDSPLY_VP_REGION_FILE_NAME_START_H                        (OSDDSPLY_VP_START_H+8)
#define OSDDSPLY_VP_REGION_FILE_NAME_START_V                        OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_FILE_NAME_WIDTH                          320
#define OSDDSPLY_VP_REGION_FILE_NAME_HEIGHT                         OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_FILE_NAME_ITEM_COLOR                     OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_ITEM
#define OSDDSPLY_VP_REGION_FILE_NAME_INFO_COLOR                     OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_INFO

//define the distance between the file name and file num
#define OSDDSPLY_VP_DISTANCE_REGION_FILE_NAME_FILE_NUM              8

//define the distance between the file num and the status.
#define OSDDSPLY_VP_DISTANCE_REGION_FILE_NUM_STATUS                 0//8

//"File Num" Region: display JPEG file num
#define OSDDSPLY_VP_REGION_FILE_NUM_START_H                         (OSDDSPLY_VP_REGION_FILE_NAME_START_H+OSDDSPLY_VP_REGION_FILE_NAME_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_FILE_NAME_FILE_NUM)
#define OSDDSPLY_VP_REGION_FILE_NUM_START_V                         OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_FILE_NUM_WIDTH                           (OSDDSPLY_VP_REGION_PROGRAM_STATUS_START_H-OSDDSPLY_VP_REGION_FILE_NUM_START_H-OSDDSPLY_VP_DISTANCE_REGION_FILE_NUM_STATUS)//160
#define OSDDSPLY_VP_REGION_FILE_NUM_HEIGHT                          OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_FILE_NUM_ITEM_COLOR                      OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_ITEM
#define OSDDSPLY_VP_REGION_FILE_NUM_INFO_COLOR                      OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_INFO

//"Resolution" Region: display JPEG resolution
#define OSDDSPLY_VP_REGION_RESOLUTION_START_H                       (OSDDSPLY_VP_START_H+8)
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_RESOLUTION_START_V                       OSDDSPLY_VP_REGION_LINE_0_START_V
#else
#define OSDDSPLY_VP_REGION_RESOLUTION_START_V                       OSDDSPLY_VP_REGION_LINE_1_START_V
#endif //SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_RESOLUTION_WIDTH                         248
#define OSDDSPLY_VP_REGION_RESOLUTION_HEIGHT                        OSDDSPLY_VP_REGION_LINE_1_HEIGHT
#define OSDDSPLY_VP_REGION_RESOLUTION_ITEM_COLOR                    OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_ITEM
#define OSDDSPLY_VP_REGION_RESOLUTION_INFO_COLOR                    OSDDSPLY_VP_PALETTE_ENTRY_REGION_RESOLUTION_INFO

//"Date" Region: display JPEG resolution
#define OSDDSPLY_VP_REGION_DATE_START_H                             OSDDSPLY_VP_REGION_FILE_NUM_START_H
#ifdef SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_DATE_START_V                             OSDDSPLY_VP_REGION_LINE_0_START_V
#else
#define OSDDSPLY_VP_REGION_DATE_START_V                             OSDDSPLY_VP_REGION_LINE_1_START_V
#endif //SUPPORT_SIMPLE_DISPLAY_MODE
#define OSDDSPLY_VP_REGION_DATE_WIDTH                               240
#define OSDDSPLY_VP_REGION_DATE_HEIGHT                              OSDDSPLY_VP_REGION_LINE_1_HEIGHT
#define OSDDSPLY_VP_REGION_DATE_ITEM_COLOR                          OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_ITEM
#define OSDDSPLY_VP_REGION_DATE_INFO_COLOR                          OSDDSPLY_VP_PALETTE_ENTRY_REGION_DATE_INFO

//"File Name" Region: display JPEG file name
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_START_H                 (OSDDSPLY_VP_START_H+12)
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_START_V                 OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_WIDTH                   288
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_HEIGHT                  OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_ITEM_COLOR              OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_ITEM
#define OSDDSPLY_VP_REGION_MOTION_FILE_NAME_INFO_COLOR              OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NAME_INFO

//define the distance between the file name and file num
#define OSDDSPLY_VP_DISTANCE_REGION_MOTION_FILE_NAME_FILE_NUM       0

//"File Num" Region: display motion file num
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_START_H                  (OSDDSPLY_VP_REGION_MOTION_FILE_NAME_START_H+OSDDSPLY_VP_REGION_MOTION_FILE_NAME_WIDTH+OSDDSPLY_VP_DISTANCE_REGION_MOTION_FILE_NAME_FILE_NUM)
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_START_V                  OSDDSPLY_VP_REGION_LINE_0_START_V
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_WIDTH                    (OSDDSPLY_VP_REGION_PROGRAM_STATUS_START_H-OSDDSPLY_VP_REGION_MOTION_FILE_NUM_START_H-OSDDSPLY_VP_DISTANCE_REGION_FILE_NUM_STATUS)
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_HEIGHT                   OSDDSPLY_VP_REGION_LINE_0_HEIGHT
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_ITEM_COLOR               OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_ITEM
#define OSDDSPLY_VP_REGION_MOTION_FILE_NUM_INFO_COLOR               OSDDSPLY_VP_PALETTE_ENTRY_REGION_FILE_NUM_INFO

//Define the distance between "file num" and "time"
#define OSDDSPLY_VP_DISTANCE_REGION_MOTION_FILE_NUM_TIME            0

//"Time" Region: display the time for CDROM motion
#define OSDDSPLY_VP_REGION_MOTION_TIME_START_H                      OSDDSPLY_VP_REGION_AST_START_H
#define OSDDSPLY_VP_REGION_MOTION_TIME_START_V                      OSDDSPLY_VP_REGION_LINE_2_START_V
#define OSDDSPLY_VP_REGION_MOTION_TIME_WIDTH                        120
#define OSDDSPLY_VP_REGION_MOTION_TIME_HEIGHT                       OSDDSPLY_VP_REGION_LINE_2_HEIGHT
#define OSDDSPLY_VP_REGION_MOTION_TIME_COLOR                        OSDDSPLY_VP_PALETTE_ENTRY_REGION_TIME

//***************************************************************************
//Navigator
//***************************************************************************
//#define SUPPORT_REPEAT_SUBTITLE
// wyc2.17-909S,
#if (SLOW_MODE_CONFIG != NORMAL_SLOW_MODE)
#define SUPPORT_SEPARATOR
#endif

typedef struct tagNAVIGATOR
{
    BYTE bIconID;
    BYTE bIconAttr;
    BYTE *bPopMenuAction;
    WORD wPopMenuStartPosH;
    WORD wPopMenuStartPosV;
} NAVIGATOR, *PNAVIGATOR;

#define OSDDSPLY_MAX_NAVIGATOR_BMP_NUM				9

#define OSDDSPLY_NAVIGATOR_BMP_NG_AUDIO				0
#define OSDDSPLY_NAVIGATOR_BMP_NG_ANGLE				1
#define OSDDSPLY_NAVIGATOR_BMP_NG_CHAPTER			2
#define OSDDSPLY_NAVIGATOR_BMP_NG_REPEAT			3
#define OSDDSPLY_NAVIGATOR_BMP_NG_SUBTITLE1			4
#define OSDDSPLY_NAVIGATOR_BMP_NG_SUBTITLE2			5
#define OSDDSPLY_NAVIGATOR_BMP_NG_TITLE				6
#define OSDDSPLY_NAVIGATOR_BMP_NG_REPEATAB		    7
#define OSDDSPLY_NAVIGATOR_BMP_NG_SLOW				8

//Define the time to show the tip.
#define  OSDDSPLY_NAVIGATOR_SHOW_TIP_TIME           COUNT_3_SEC

//Define total icons
// wyc2.17-909S,
#if (SLOW_MODE_CONFIG != NORMAL_SLOW_MODE)
#define OSDDSPLY_NAVIGATOR_TOTAL_ICONS              8
#else
#define OSDDSPLY_NAVIGATOR_TOTAL_ICONS              7
#endif

//define the icon's attribute
#define OSDDSPLY_NAVIGATOR_ICON_ATTRIBUTE_POPUP_MENU    0
#define OSDDSPLY_NAVIGATOR_ICON_ATTRIBUTE_BUTTON        1 

//Open this define to support round highlight in the icon part
#define  OSDDSPLY_NAVIGATOR_SUPPORT_ROUND_HIGHLIGHT

//Define the parameters for draw/clear
#define  OSDDSPLY_NAVIGATOR_UPDATE_DRAW             0
#define  OSDDSPLY_NAVIGATOR_UPDATE_CLEAR            1       

//Define the cursor's position.
#define  OSDDSPLY_NAVIGATOR_CURSOR_POS_ICON         0                         
#define  OSDDSPLY_NAVIGATOR_CURSOR_POS_MENU         1                         

//Define the icon's ID
#define OSDDSPLY_NAVIGATOR_ICON_TITLE               0
#define OSDDSPLY_NAVIGATOR_ICON_CHAPTER             1
#define OSDDSPLY_NAVIGATOR_ICON_AUDIO               2
#define OSDDSPLY_NAVIGATOR_ICON_SPST1               3
#define OSDDSPLY_NAVIGATOR_ICON_SPST2               4
#define OSDDSPLY_NAVIGATOR_ICON_ANGLE               5
#define OSDDSPLY_NAVIGATOR_ICON_REPEAT              6
#define OSDDSPLY_NAVIGATOR_ICON_REPEATAB            7
#define OSDDSPLY_NAVIGATOR_ICON_SLOW                8

    
//Define the next/previous action 
#define OSDDSPLY_NAVIGATOR_NEXT_ACTION              KEY_DOWN
#define OSDDSPLY_NAVIGATOR_PREVIOUS_ACTION          KEY_UP
#define OSDDSPLY_NAVIGATOR_CANCEL_MENU_ACTION       KEY_LEFT

//Define the frame for the icons
#define OSDDSPLY_NAVIGATOR_ICON_FRAME_THICKNESS     4

//Define the icon-relative attributes
#define OSDDSPLY_NAVIGATOR_ICON_MENU_DISTANCE       16
#define OSDDSPLY_NAVIGATOR_ICON_START_H             16
#ifdef OSDDSPLY_NAVIGATOR_SUBMENU_START_FROM_ICON_TOP
#define OSDDSPLY_NAVIGATOR_ICON_START_V             (OSDND_UPPER_BACKGROUND_BOTTOM+OSDDSPLY_NAVIGATOR_MENU_ARROW_ITEM_HEIGHT+OSDDSPLY_NAVIGATOR_ICON_FRAME_THICKNESS+1)
#else
#define OSDDSPLY_NAVIGATOR_ICON_START_V             (OSDND_UPPER_BACKGROUND_BOTTOM+OSDDSPLY_NAVIGATOR_ICON_FRAME_THICKNESS+1)//42
#endif
#define OSDDSPLY_NAVIGATOR_ICON_WIDTH               48 //56
#define OSDDSPLY_NAVIGATOR_ICON_HEIGHT              40 //48 

//Define the pop-up menu starting position
#define OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H       (OSDDSPLY_NAVIGATOR_ICON_START_H+OSDDSPLY_NAVIGATOR_ICON_WIDTH+OSDDSPLY_NAVIGATOR_ICON_MENU_DISTANCE)
#ifdef OSDDSPLY_NAVIGATOR_SUBMENU_START_FROM_ICON_TOP
#define OSDDSPLY_NAVIGATOR_MENU_TITLE_START_V       (OSDDSPLY_NAVIGATOR_ICON_START_V)
#else
#define OSDDSPLY_NAVIGATOR_MENU_TITLE_START_V       (OSDDSPLY_NAVIGATOR_ICON_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#endif //OSDDSPLY_NAVIGATOR_SUBMENU_START_FROM_ICON_TOP
#define OSDDSPLY_NAVIGATOR_MENU_CHAPTER_START_H     OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_CHAPTER_START_V     (OSDDSPLY_NAVIGATOR_MENU_TITLE_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#define OSDDSPLY_NAVIGATOR_MENU_AUDIO_START_H       OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_AUDIO_START_V       (OSDDSPLY_NAVIGATOR_MENU_CHAPTER_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#define OSDDSPLY_NAVIGATOR_MENU_SPST1_START_H       OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_SPST1_START_V       (OSDDSPLY_NAVIGATOR_MENU_AUDIO_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#define OSDDSPLY_NAVIGATOR_MENU_SPST2_START_H       OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_SPST2_START_V       (OSDDSPLY_NAVIGATOR_MENU_SPST1_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#define OSDDSPLY_NAVIGATOR_MENU_ANGLE_START_H       OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_ANGLE_START_V       (OSDDSPLY_NAVIGATOR_MENU_SPST2_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
// wyc2.17-909S, add for language study
#if (SLOW_MODE_CONFIG != NORMAL_SLOW_MODE)
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_START_H      OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_START_V      (OSDDSPLY_NAVIGATOR_MENU_SPST2_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#else
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_START_H      OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_START_V      (OSDDSPLY_NAVIGATOR_MENU_ANGLE_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#endif // SLOW_MODE_CONFIG
#define OSDDSPLY_NAVIGATOR_MENU_REPEATAB_START_H    OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_REPEATAB_START_V    (OSDDSPLY_NAVIGATOR_MENU_REPEAT_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)
#define OSDDSPLY_NAVIGATOR_MENU_SLOW_START_H        OSDDSPLY_NAVIGATOR_MENU_TITLE_START_H
#define OSDDSPLY_NAVIGATOR_MENU_SLOW_START_V        (OSDDSPLY_NAVIGATOR_MENU_REPEATAB_START_V+OSDDSPLY_NAVIGATOR_ICON_HEIGHT)


//Define the height of each menu item.
#define OSDDSPLY_NAVIGATOR_MENU_ITEM_HEIGHT         28 //32
#define OSDDSPLY_NAVIGATOR_MENU_ARROW_ITEM_HEIGHT   26
#define OSDDSPLY_NAVIGATOR_TIP_HEIGHT               28 //30
#define OSDDSPLY_NAVIGATOR_MENU_ITEM_DISTANCE_H     4

//Define the starting position to show the menu.
#define OSDDSPLY_NAVIGATOR_MENU_START_V             OSDDSPLY_NAVIGATOR_MENU_TITLE_START_V
#define OSDDSPLY_NAVIGATOR_MENU_END_V               352

//Define the max. item space
#define OSDDSPLY_NAVIGATOR_MAX_ITEM                 ((OSDDSPLY_NAVIGATOR_MENU_END_V - OSDDSPLY_NAVIGATOR_MENU_START_V)/OSDDSPLY_NAVIGATOR_MENU_ITEM_HEIGHT)

//Define the thickness of the menu main frame
#define OSDDSPLY_NAVIGATOR_MAIN_FRAME_THICKNESS     4

//Define the thickness of the separated frame
#define OSDDSPLY_NAVIGATOR_SEPARATE_FRAME_THICKNESS 4

//Define the thickness of tip's frame
#define OSDDSPLY_NAVIGATOR_TIP_FRAME_THICKNESS      2

//Define the type of the separate frame
#define OSDDSPLY_NAVIGATOR_UP_SEPARATE_FRAME        0            
#define OSDDSPLY_NAVIGATOR_DOWN_SEPARATE_FRAME      1

//Define the type of arrow
#define OSDDSPLY_NAVIGATOR_ARROW_TYPE_UP            0
#define OSDDSPLY_NAVIGATOR_ARROW_TYPE_DOWN          1

//Define the type of scroll
#define OSDDSPLY_NAVIGATOR_SCROLL_TYPE_UP           0
#define OSDDSPLY_NAVIGATOR_SCROLL_TYPE_DOWN         1

//The following paletted entries for icons should be defined in gdi.h
//Each define represents the index of the palette.
/*
#define GDI_PALETTE_ENTRY_NG_TITLE_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+99)//(GDI_BITMAP_PALETTE_INDEX_START+79) //(GDI_BITMAP_PALETTE_INDEX_START+90)
#define GDI_PALETTE_ENTRY_NG_CHAPTER_ICON                   (GDI_BITMAP_PALETTE_INDEX_START+15)//(GDI_BITMAP_PALETTE_INDEX_START+14) //(GDI_BITMAP_PALETTE_INDEX_START+53)
#define GDI_PALETTE_ENTRY_NG_AUDIO_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+103)//(GDI_BITMAP_PALETTE_INDEX_START+83) //(GDI_BITMAP_PALETTE_INDEX_START+2)
#define GDI_PALETTE_ENTRY_NG_SPST1_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+121)//(GDI_BITMAP_PALETTE_INDEX_START+100)//(GDI_BITMAP_PALETTE_INDEX_START+69)
#define GDI_PALETTE_ENTRY_NG_SPST2_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+85)//(GDI_BITMAP_PALETTE_INDEX_START+67) //(GDI_BITMAP_PALETTE_INDEX_START+39)
#define GDI_PALETTE_ENTRY_NG_ANGLE_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+124)//(GDI_BITMAP_PALETTE_INDEX_START+103)//(GDI_BITMAP_PALETTE_INDEX_START+94)
#define GDI_PALETTE_ENTRY_NG_REPEAT_ICON                    (GDI_BITMAP_PALETTE_INDEX_START+13)//(GDI_BITMAP_PALETTE_INDEX_START+12) //(GDI_BITMAP_PALETTE_INDEX_START+112)
#define GDI_PALETTE_ENTRY_NG_REPEATAB_ICON                  (GDI_BITMAP_PALETTE_INDEX_START+136)//(GDI_BITMAP_PALETTE_INDEX_START+119)
#define GDI_PALETTE_ENTRY_NG_SLOW_ICON                      (GDI_BITMAP_PALETTE_INDEX_START+77)//(GDI_BITMAP_PALETTE_INDEX_START+63)
*/
#define GDI_PALETTE_ENTRY_NG_TITLE_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+61)
#define GDI_PALETTE_ENTRY_NG_CHAPTER_ICON                   (GDI_BITMAP_PALETTE_INDEX_START+17)
#define GDI_PALETTE_ENTRY_NG_AUDIO_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+3)
#define GDI_PALETTE_ENTRY_NG_SPST1_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+78)
#define GDI_PALETTE_ENTRY_NG_SPST2_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+1)
#define GDI_PALETTE_ENTRY_NG_ANGLE_ICON                     (GDI_BITMAP_PALETTE_INDEX_START+82)
#define GDI_PALETTE_ENTRY_NG_REPEAT_ICON                    (GDI_BITMAP_PALETTE_INDEX_START+2)
#define GDI_PALETTE_ENTRY_NG_REPEATAB_ICON                  (GDI_BITMAP_PALETTE_INDEX_START+4)
#define GDI_PALETTE_ENTRY_NG_SLOW_ICON                      (GDI_BITMAP_PALETTE_INDEX_START+5)

//define the fixed palette entry for the icons
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_TITLE_BACKGROUND     GDI_PALETTE_ENTRY_NG_TITLE_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_CHAPTER_BACKGROUND   GDI_PALETTE_ENTRY_NG_CHAPTER_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_AUDIO_BACKGROUND     GDI_PALETTE_ENTRY_NG_AUDIO_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_SPST1_BACKGROUND     GDI_PALETTE_ENTRY_NG_SPST1_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_SPST2_BACKGROUND     GDI_PALETTE_ENTRY_NG_SPST2_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_ANGLE_BACKGROUND     GDI_PALETTE_ENTRY_NG_ANGLE_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_REPEAT_BACKGROUND    GDI_PALETTE_ENTRY_NG_REPEAT_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_REPEATAB_BACKGROUND  GDI_PALETTE_ENTRY_NG_REPEATAB_ICON
#define OSDDSPLY_NG_PALETTE_ENTRY_ICON_SLOW_BACKGROUND      GDI_PALETTE_ENTRY_NG_SLOW_ICON

//define the color for icon's state.
#define OSDDSPLY_NG_PALETTE_COLOR_ICON_NORMAL_BACKGROUND    0xC0C0C0
#define OSDDSPLY_NG_PALETTE_COLOR_ICON_HIGHLIGHT_BACKGROUND 0xFFD900//0xFFA928
#define OSDDSPLY_NG_PALETTE_COLOR_ICON_PRESSED_BACKGROUND   0x006900

//define the palette entry
#define OSDDSPLY_NG_PALETTE_ENTRY_START                     (OSDDSPLY_VP_PALETTE_ENTRY_END+1)
#define OSDDSPLY_NG_PALETTE_ENTRY_GENERAL_BACKGROUND        OSDDSPLY_NG_PALETTE_ENTRY_START
#define OSDDSPLY_NG_PALETTE_ENTRY_NORMAL_FRAME_BRIGHT       (OSDDSPLY_NG_PALETTE_ENTRY_START+1)                 
#define OSDDSPLY_NG_PALETTE_ENTRY_NORMAL_FRAME_DARK         (OSDDSPLY_NG_PALETTE_ENTRY_START+2)                   
#define OSDDSPLY_NG_PALETTE_ENTRY_SEPARATE_FRAME_CENTER     (OSDDSPLY_NG_PALETTE_ENTRY_START+3)               
#define OSDDSPLY_NG_PALETTE_ENTRY_MENU_HIGHLIGHT            (OSDDSPLY_NG_PALETTE_ENTRY_START+4)
#define OSDDSPLY_NG_PALETTE_ENTRY_MENU_ITEM_TEXT            (OSDDSPLY_NG_PALETTE_ENTRY_START+5)
#define OSDDSPLY_NG_PALETTE_ENTRY_TIP_FRAME_BRIGHT          (OSDDSPLY_NG_PALETTE_ENTRY_START+6)                 
#define OSDDSPLY_NG_PALETTE_ENTRY_TIP_FRAME_DARK            (OSDDSPLY_NG_PALETTE_ENTRY_START+7)
#define OSDDSPLY_NG_PALETTE_ENTRY_TIP_BACKGROUND            (OSDDSPLY_NG_PALETTE_ENTRY_START+8)                   
                 

//define the palette color
#define OSDDSPLY_NG_PALETTE_COLOR_GENERAL_BACKGROUND        0xC0C0C0     
#define OSDDSPLY_NG_PALETTE_COLOR_NORMAL_FRAME_BRIGHT       0xFFFFFF                 
#define OSDDSPLY_NG_PALETTE_COLOR_NORMAL_FRAME_DARK         0x202020                   
#define OSDDSPLY_NG_PALETTE_COLOR_SEPARATE_FRAME_CENTER     0xC0C0C0               
#define OSDDSPLY_NG_PALETTE_COLOR_MENU_HIGHLIGHT            0xFFA928
#define OSDDSPLY_NG_PALETTE_COLOR_MENU_ITEM_TEXT            0x010101
#define OSDDSPLY_NG_PALETTE_COLOR_TIP_FRAME_BRIGHT          0x010101                 
#define OSDDSPLY_NG_PALETTE_COLOR_TIP_FRAME_DARK            0x010101
#define OSDDSPLY_NG_PALETTE_COLOR_TIP_BACKGROUND            0xFFFF66       

//define the items in "Repeat" menu.
#ifdef SUPPORT_REPEAT_SUBTITLE
#define OSDDSPLY_NAVIGATOR_MENU_TOTAL_ITEM                  5
#else
#define OSDDSPLY_NAVIGATOR_MENU_TOTAL_ITEM                  4
#endif //SUPPORT_REPEAT_SUBTITLE
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_TITLE                0
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_CHAPTER              1
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_DISC                 2
#ifdef SUPPORT_REPEAT_SUBTITLE
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_SUBTITLE             3
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_OFF                  4
#else
#define OSDDSPLY_NAVIGATOR_MENU_REPEAT_OFF                  3
#endif //SUPPORT_REPEAT_SUBTITLE

//define the max. right porint for Navigator UI
#define OSDDSPLY_NAVIGATOR_MAX_RIGHT_PROINT					500

//***************************************************************************
//Function declaration
//***************************************************************************

//Export functions
BYTE OSDDSPLY_Update(BYTE bMessage, WORD wParam);
// LLY2.53, expand time value unit from WORD to DWORD
//void OSDDSPLY_Trigger(BYTE bType, WORD wTime);
void OSDDSPLY_Trigger(BYTE bType, DWORD dwTime);
BYTE OSDDSPLY_Recover(BYTE bRecoverRegion);
BYTE OSDDSPLY_ProcessKey(void);
void OSDDSPLY_Exit(BYTE bExitMode);
void OSDDSPLY_NAVIGATOR_ClearMenuForNVChange(BYTE bMessage); //CoCo1.11
#ifdef SUPPORT_INDEPENDENT_NAVIGATOR //CoCo1.0, support independent Navigator UI
void OSDDSPLY_NAVIGATOR_Exit(BYTE bExitMode);
BYTE OSDNAVIGATOR_Recover(BYTE bRecoverRegion);
// LLY2.53, expand time value unit from WORD to DWORD
//void OSDNAVIGATOR_Trigger(BYTE bType, WORD wTime);
void OSDNAVIGATOR_Trigger(BYTE bType, DWORD dwTime);
#endif
void OSDDSPLY_ConfigOSDRegion(void);

//Internal functions
//The internal functions for common usage.
void _OSDDSPLY_ClearDisplayModeUI(void);
void _OSDDSPLY_SwitchDisplayModeUI(void);
void _OSDDSPLY_ShowDisplayModeUI(BYTE bRecoverUI);
void _OSDDSPLY_OutputString(BYTE bMessage);
BYTE _OSDDSPLY_GetInfoPos(BYTE bMessage);
void _OSDDSPLY_ShowTitleInfo(void);
#ifndef NO_DISC_MODE //CoCo2.37   
void _OSDDSPLY_ShowTitleMenu(void);
#endif //#ifndef NO_DISC_MODE //CoCo2.37  
void _OSDDSPLY_ShowChapterInfo(void);
void _OSDDSPLY_ShowTrackInfo(void);
void _OSDDSPLY_CodeToLanguage(WORD wCode);
void _OSDDSPLY_ShowSPST1Info(BYTE bNavigatorUI);
void _OSDDSPLY_ShowASTInfo(void);
void _OSDDSPLY_ShowAngleInfo(void);
void _OSDDSPLY_ShowPlayingStatus(void);
void _OSDDSPLY_ShowTVInfo(void);
BYTE _OSDDSPLY_SameTimeType(BYTE bMessage);
void _OSDDSPLY_DrawBackground(BYTE bBackgroundType);
void _OSDDSPLY_ClearBackground(BYTE bBackgroundType);
void _OSDDSPLY_InitializeGDI(void);
void _OSDDSPLY_SetBackground(BYTE bBackgroundType);
WORD _OSDDSPLY_ShowDirNameInfo(WORD wMaxLength);
WORD _OSDDSPLY_ShowFileNameInfo(WORD wMaxLength);

//The internal functions for virtual panel.
BYTE _OSDDSPLY_VP_Update(BYTE bMessage);
void _OSDDSPLY_VP_ShowItem(BYTE bMessage);
BYTE _OSDDSPLY_VP_ShowInfo(BYTE bMessage);
BYTE _OSDDSPLY_VP_GetRegion(BYTE bMessage);
void _OSDDSPLY_VP_ClearRegion(BYTE bClearRegion, BYTE bPos);
void _OSDDSPLY_VP_DrawRegion(BYTE bRegion, BYTE bType, BYTE bPos);
void _OSDDSPLY_VP_ShowTime(void);
void _OSDDSPLY_VP_UpdateUnknownRegions(void);
void _OSDDSPLY_VP_ShowDVDMode(void);
void _OSDDSPLY_VP_ShowJPEGMode(void);
void _OSDDSPLY_VP_ShowDIVXMode(void);
void _OSDDSPLY_VP_MOTION_ShowTime(void);
void _OSDDSPLY_VP_ShowFileNameInfo(WORD wMaxLength, WORD wHPos);

//The internal functions for one-line Display UI.
BYTE _OSDDSPLY_LD_Update(BYTE bMessage);
void _OSDDSPLY_LD_Show(BYTE bRecoverUI);
void _OSDDSPLY_LD_ShowTime(BYTE bUpdate);
void _OSDDSPLY_LD_ShowSpecialTimeMode(void);
void _OSDDSPLY_LD_DrawRegion(BYTE bRegion, BYTE bType, BYTE bPos);
void _OSDDSPLY_LD_ShowItem(BYTE bMessage);
BYTE _OSDDSPLY_LD_GetRegion(BYTE bMessage);
void _OSDDSPLY_LD_ShowInfo(BYTE bMessage);
void _OSDDSPLY_LD_ClearRegion(BYTE bClearRegion, BYTE bPos);
void _OSDDSPLY_LD_UpdateUnknownRegions(void);
void _OSDDSPLY_LD_ShowUnknownTrack(void);
BYTE _OSDDSPLY_LD_SpecialTimeModeUpdate(BYTE bMessage);
void _OSDDSPLY_LD_SetTimeType(void);
void _OSDDSPLY_LD_ShowFileNameInfo(WORD wMaxLength, WORD wHPos);

//The internal functions for Navigator
BYTE _OSDDSPLY_NAVIGATOR_PopupMenuKey(BYTE bKey);
void _OSDDSPLY_NAVIGATOR_InitializeMenuAttribute(void);
void _OSDDSPLY_NAVIGATOR_ClearItemRegion(BYTE bIndex, BYTE bHighlight);
void _OSDDSPLY_NAVIGATOR_DrawMenu(void);
void _OSDDSPLY_NAVIGATOR_DrawSeparateFrame(BYTE bFrameType);
WORD _OSDDSPLY_NAVIGATOR_GetMaxWidthInMenu(void);
void _OSDDSPLY_NAVIGATOR_CalculateMaxNumWidth(WORD wMaxNum);
void _OSDDSPLY_NAVIGATOR_CalculateMaxRepeatWidth(void);
void _OSDDSPLY_NAVIGATOR_GetRepeatItem(BYTE bIndex);
BYTE _OSDDSPLY_NAVIGATOR_TransformRepeatItem(void);
void _OSDDSPLY_NAVIGATOR_PrepareMenuInfo(void);
void _OSDDSPLY_NAVIGATOR_SetCommonItemStringAttribute(void);
void _OSDDSPLY_NAVIGATOR_DrawAllItems(void);
void _OSDDSPLY_NAVIGATOR_UpdateUpDownArraow(BYTE bArrowType);
void _OSDDSPLY_NAVIGATOR_Scroll(BYTE bScrollType);
void _OSDDSPLY_NAVIGATOR_DrawMenuItem(BYTE bIndex, BYTE bHighlight);
void _OSDDSPLY_NAVIGATOR_DrawUpDownArrowBackground(BYTE bArrowType);
void _OSDDSPLY_NAVIGATOR_ClearUpDownArrowBackground(BYTE bArrowType);
void _OSDDSPLY_NAVIGATOR_DrawMainFrame(void);
void _OSDDSPLY_NAVIGATOR_ClearMenu(void);
void _OSDDSPLY_NAVIGATOR_ShowTip(void);
void _OSDDSPLY_NAVIGATOR_DrawTipString(void);
void _OSDDSPLY_NAVIGATOR_ClearTip(void);
void _OSDDSPLY_NAVIGATOR_ClearIconHighlight(void);
void _OSDDSPLY_NAVIGATOR_ShowIconHighlight(void);
void _OSDDSPLY_NAVIGATOR_ChangeIconCursor(BYTE bIconID);
void _OSDDSPLY_NAVIGATOR_PopupMenu(void);
BYTE _OSDDSPLY_NAVIGATOR_ProcessSpecialKeyForIcon(BYTE bIconID);
BYTE _OSDDSPLY_NAVIGATOR_MoveCursorToNextMenuItem(void);
BYTE _OSDDSPLY_NAVIGATOR_MoveCursorToPreviousMenuItem(void);
BYTE _OSDDSPLY_NAVIGATOR_ProcessSpecialKeyForMenu(BYTE bIconID);
void _OSDDSPLY_NAVIGATOR_SetTipString(void);
BYTE _OSDDSPLY_NAVIGATOR_CheckValidPopupMenu(void);
BYTE _OSDDSPLY_NAVIGATOR_ChangeSetting(void);
void _OSDDSPLY_NAVIGATOR_SetRepeatSetting(void);
void _OSDDSPLY_NAVIGATOR_CalculateMaxAudioMenuWidth(void);
void _OSDDSPLY_NAVIGATOR_CalculateMaxSPST1MenuWidth(void);
void _OSDDSPLY_NAVIGATOR_GetASTInfo(BYTE bASTNO);
void _OSDDSPLY_NAVIGATOR_ChangeTitleSetting(void);
void _OSDDSPLY_NAVIGATOR_ShowSPST2Info(void);
void _OSDDSPLY_NAVIGATOR_ShowNavigator(void);
void _OSDDSPLY_NAVIGATOR_InitializeGDI(void);
void _OSDDSPLY_NAVIGATOR_ProcessButton(void);
void _OSDDSPLY_NAVIGATOR_DrawIconSeparateFrame(void);
BYTE _OSDDSPLY_NAVIGATOR_SeparatorHeight(BYTE bIconIndex);
BYTE _OSDDSPLY_NAVIGATOR_TotalSeparatorHeight(void);
void _OSDDSPLY_DrawString(void);
#ifdef SUPPORT_UNICODE_CODING
void _OSDDSPLY_DrawStringByUnicode(void);
#endif
void _OSDDSPLY_NAVIGATOR_ClearMenuRegion(void);


#endif //__OSDDSPLY_H__
