#ifndef __MAIN_MENU_H__
#define __MAIN_MENU_H__

#ifdef SUPPORT_STB
#ifdef IMAGE_FRAME_SETUP
#include "OSDString\\strextrn.h"
#else
#include "..\\..\\OSDString\\strextrn.h"
#endif //IMAGE_FRAME_SETUP
#else
#include "OSDString\\strextrn.h"
#endif //SUPPORT_STB

#ifdef SUPPORT_STB
//extern
#ifdef SUPPORT_GAME_MINER
extern void GAME_MINE_Initial(void);
extern BYTE GAME_MINE_ProcessKey(BYTE bKey);
extern void GAME_MINE_Trigger(void);
extern void GAME_MINE_Exit(BYTE bClearBackground);
#endif //SUPPORT_GAME_MINER

#ifdef SUPPORT_GAME_TETRIS
extern void GAME_TETRIS_Initial(void);
extern BYTE GAME_TETRIS_ProcessKey(BYTE bKey);
extern void GAME_TETRIS_Trigger(void);
extern void GAME_TETRIS_Exit(BYTE bClearBackground);
#endif //SUPPORT_GAME_TETRIS

#ifdef SUPPORT_GAME_GOMOKU
extern void GAME_GOMOKU_Initial(void);
extern BYTE GAME_GOMOKU_ProcessKey(BYTE bKey);
extern void GAME_GOMOKU_Exit(BYTE bClearBackground);
#endif //SUPPORT_GAME_GOMOKU

#ifdef SUPPORT_GAME_SOKOBAN
extern void GAME_SOKOBAN_Initial(void);
extern BYTE GAME_SOKOBAN_ProcessKey(BYTE bKey);
extern void GAME_SOKOBAN_Trigger(void);
extern void GAME_SOKOBAN_Exit(BYTE bClearBackground);
#endif //SUPPORT_GAME_SOKOBAN

#ifdef SUPPORT_GAME_RUSHHOUR
extern void GAME_RUSHHOUR_Initial(void);
extern BYTE GAME_RUSHHOUR_ProcessKey(BYTE bKey);
extern void GAME_RUSHHOUR_Exit(BYTE bClearBackground);
#endif //SUPPORT_GAME_RUSHHOUR

#ifndef SUPPORT_POWERON_MENU
#ifdef SUPPORT_CALENDAR
extern void CALENDAR_Initial(void);
extern BYTE CALENDAR_ProcessKey(BYTE bKey);
extern void CALENDAR_Exit(BYTE bClearBackground);
#endif //SUPPORT_CALENDAR   
#endif //SUPPORT_POWERON_MENU

#endif //#ifdef SUPPORT_STB

//define the region of the title background
#define MAINMENU_TITLE_REGION_START_X			            0
#define MAINMENU_TITLE_REGION_START_Y			            0
#define MAINMENU_TITLE_REGION_WIDTH				            616
#define MAINMENU_TITLE_REGION_HEIGHT			            36

//define the region of the menu content background
#define MAINMENU_CONTENT_REGION_START_X			            MAINMENU_TITLE_REGION_START_X
#define MAINMENU_CONTENT_REGION_START_Y			            (MAINMENU_TITLE_REGION_START_Y+MAINMENU_TITLE_REGION_HEIGHT)
#define MAINMENU_CONTENT_REGION_WIDTH			            MAINMENU_TITLE_REGION_WIDTH
#define MAINMENU_CONTENT_REGION_HEIGHT			            320

//define the region of the menu help background
#define MAINMENU_HELP_REGION_START_X			            MAINMENU_TITLE_REGION_START_X
#define MAINMENU_HELP_REGION_START_Y			            (MAINMENU_CONTENT_REGION_START_Y+MAINMENU_CONTENT_REGION_HEIGHT)
#define MAINMENU_HELP_REGION_WIDTH				            MAINMENU_TITLE_REGION_WIDTH
#define MAINMENU_HELP_REGION_HEIGHT				            36//42	

#define MAINMENU_HELP_BACKGROUND_STRING_DISTANCE_H          20
#define MAINMENU_HELP_STRING_START_X                        (MAINMENU_HELP_REGION_START_X+MAINMENU_HELP_BACKGROUND_STRING_DISTANCE_H)
#define MAINMENU_HELP_ICON_DISTANCE_H                       4                        

#define MAINMENU_HELP_SELECT_EXIT_DISTANCE_H                12

#define MAINMENU_TITLE_REGION_STRING_DISTANCE_H             20
#define MAINMENU_TITLE_STRING_START_X			            (MAINMENU_TITLE_REGION_START_X+MAINMENU_TITLE_REGION_STRING_DISTANCE_H)
#define MAINMENU_TITLE_STRING_REGION_WIDTH                  (MAINMENU_TITLE_REGION_WIDTH-MAINMENU_TITLE_REGION_STRING_DISTANCE_H*2)

#define MAINMENU_TITLE_REGION_ARC                           19
#define MAINMENU_HELP_REGION_ARC                            19

#ifdef SUPPORT_STB
//define the distance between the button and the string.
#define MAINMENU_BUTTON_STRING_DISTANCE_H                   24

//define the distance between the background and button.
#define MAINMENU_BUTTON_BACKGROUND_DISTANCE_V               40

//Define the height of the button
#define MAINMENU_BUTTON_HEIGHT                              30

#define MAINMENU_BUTTON_ARC_VALUE                           19

#endif //#ifdef SUPPORT_STB

#define MAINMENU_TITLE_BACKGROUND_PALETTE_ENTRY_BERIN		GDI_MAIN_MENU_PALETTE_INDEX_START
#define MAINMENU_TITLE_BACKGROUND_PALETTE_RESERVE_NUM       16
#define MAINMENU_HELP_BACKGROUND_PALETTE_ENTRY_BEGIN		(MAINMENU_TITLE_BACKGROUND_PALETTE_ENTRY_BERIN+MAINMENU_TITLE_BACKGROUND_PALETTE_RESERVE_NUM)
#define MAINMENU_HELP_BACKGROUND_PALETTE_RESERVE_NUM        16

#ifdef SUPPORT_STB
//define the type of the button
#define MAINMENU_BUTTON_NORMAL                  0
#define MAINMENU_BUTTON_HIGHLIGHT               1
#define MAINMENU_BUTTON_DISABLE                 2
#endif //#ifdef SUPPORT_STB

//define the invalid entry of menu flow table
#define MAINMENU_INVALID_MENU_FLOW_ENTRY        0xFF

#ifdef SUPPORT_STB
//define the invalid menu state
#define MAINMENU_INVALID_MENU_STATE             0xFF

#define MAINMENU_INVALID_DLG_SATE               0xFF

#define DLG_ACTION_DONE					        0
#define DLG_ACTION_EXIT_RECOVER_NENU            1
#define DLG_ACTION_EXIT_NEW_NENU                2
#define DLG_ACTION_CHANGE_DLG                   3
#define DLG_ACTION_FORCE_EXIT                   4

//define state in menu
typedef enum tagMENU_STATE_ITEM
{
    //Main menu
    MS_MAIN_MENU = 0,
    MS_DVD_SETUP,
    MS_DVB_MENU,
    MS_SYSTEM_SETTING,
    MS_GAME,
    //STB menu
    MS_DVB_TV_PROGRAM,
    MS_DVB_MUSIC_PROGRAM,
    MS_DVB_AUTO_SEARCH,
    MS_DVB_MANUAL_SEARCH,
    MS_DLG,
    MS_DVB_PARENTAL_SETTING,
    MS_DVB_LANGUAGE,
    MS_DVB_TIME_SETTING,
    MS_DVB_SCHEDULE,    
    MS_DVB_SCHEDULE_TIME_SETTING,
    //Game menu
    MS_GAME_MINE,
    MS_GAME_TETRIS,
    MS_GAME_GOMOKU,
    MS_GAME_SOKOBAN, //xuli.osdgame
    MS_GAME_RUSHHOUR, //xuli.osdgame
#ifndef SUPPORT_POWERON_MENU
    MS_CALENDAR,
#endif //SUPPORT_POWERON_MENU
} MENU_STATE_ITEM;

typedef enum tagDLG_STATE_ITEM
{
    DS_PIN_DLG_CHANNEL_LOCK = 0,
    DS_PIN_DLG_PARENTAL_SETTING,
#ifndef IMAGE_FRAME_SETUP
    DS_PIN_DLG_DVD_PARENTAL_LEVEL,
    DS_DVD_LANGUAGE_CODE_DLG,
#endif //IMAGE_FRAME_SETUP
    //system setting
    DS_DCHANGE_PIN_DLG,
} DLG_STATE_ITEM;

typedef struct tagMENU_STATE
{
    MENU_STATE_ITEM MenuCurrentState;
    MENU_STATE_ITEM MenuChangeToStateAfterExit;
} MENU_STATE;   

typedef struct tagMENU_FLOW
{
    MENU_STATE_ITEM MenuState;
    void (*Menu_Init_Func_Ptr)(void);
    BYTE (*Menu_Proc_Func_Ptr)(BYTE);
    void (*Menu_Trigger_Func_Ptr)(void);
    void (*Menu_Recover_Func_Ptr)(void);
    void (*Menu_Exit_Func_Ptr)(BYTE);   
} MENU_FLOW, *PMENU_FLOW;

typedef struct tagBUTTON
{
    BYTE bButtonID;
    //WORD *pwButtonString[OSD_LANGUAGE_NUMBER];
    WORD *pwButtonString;
} BUTTON, *PBUTTON;

//define the button ID
typedef enum tagBUTTON_ID
{
    MAINMENU_BUTTON_DVD_SETUP = 0,
    MAINMENU_BUTTON_DVB_MENU,
    MAINMENU_BUTTON_SYSTEM_SETTING,
#ifndef SUPPORT_POWERON_MENU
    MAINMENU_BUTTON_GAME,
    MAINMENU_BUTTON_EXIT,
    MAINMENU_BUTTON_NUM,
#else
    MAINMENU_BUTTON_EXIT,
    MAINMENU_BUTTON_NUM,
    MAINMENU_BUTTON_GAME,
#endif //SUPPORT_POWERON_MENU

} BUTTON_ID;

typedef enum tagGAME_BUTTON_ID
{
#ifdef SUPPORT_GAME_MINER
    MAINMENU_GAME_BUTTON_MINE = 0,
#endif
#ifdef SUPPORT_GAME_TETRIS
    MAINMENU_GAME_BUTTON_TETRIS,
#endif
#ifdef SUPPORT_GAME_GOMOKU
    MAINMENU_GAME_BUTTON_GOMOKU,
#endif
#ifdef SUPPORT_GAME_SOKOBAN
    MAINMENU_GAME_BUTTON_SOKOBAN,  //xuli.osdgame
#endif
#ifdef SUPPORT_GAME_RUSHHOUR
    MAINMENU_GAME_BUTTON_RUSHHOUR,    //xuli.osdgame
#endif
#ifndef SUPPORT_POWERON_MENU
#ifdef SUPPORT_CALENDAR
    MAINMENU_GAME_BUTTON_CALENDAR,
#endif //SUPPORT_CALENDAR    
#endif //SUPPORT_POWERON_MENU
    MAINMENU_GAME_BUTTON_EXIT,
    MAINMENU_GAME_BUTTON_NUM
} GAME_BUTTON_ID;

typedef struct tagDLG_FLOW
{
    void (*Dlg_Init_Func_Ptr)(BYTE);
    BYTE (*Dlg_Proc_Func_Ptr)(BYTE);
    void (*Dlg_Trigger_Func_Ptr)(void);
    void (*Dlg_Recover_Func_Ptr)(void);
    void (*Dlg_Exit_Func_Ptr)(void);
    void (*Dlg_Call_Back_Ptr)(BYTE);
    BYTE bRecoverMenuState;
    BYTE bNewMenuState;
    BYTE bChangeDlgState;
} DLG_FLOW, *PDLG_FLOW;

typedef enum tagMAINMENU_NORMAL_BUTTON_PALETTE
{
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_BEGIN = GDI_BITMAP_PALETTE_INDEX_START,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0 = MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_BEGIN,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_14,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_END,
} MAINMENU_NORMAL_BUTTON_PALETTE;

typedef enum tagMAINMENU_HIGHLIGHT_BUTTON_PALETTE
{
    MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_BEGIN = MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_END,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0 = MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_BEGIN,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_14,
    MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_END,
} MAINMENU_HIGHLIGHT_BUTTON_PALETTE;

typedef enum tagMAINMENU_DISABLE_BUTTON_PALETTE
{
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_BEGIN = MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_END,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_0 = MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_BEGIN,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_14,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_END,
} MAINMENU_DISABLE_BUTTON_PALETTE;

#endif //#ifdef SUPPORT_STB

typedef enum tagMAINMENU_TITLE_REGION_PALETTE
{
    MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0 = MAINMENU_TITLE_BACKGROUND_PALETTE_ENTRY_BERIN,
    MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_14
} MAINMENU_TITLE_REGION_PALETTE;

typedef enum tagMAINMENU_HELP_REGION_PALETTE
{
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0 = MAINMENU_HELP_BACKGROUND_PALETTE_ENTRY_BEGIN,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_14
} MAINMENU_HELP_REGION_PALETTE;

#define MAINMENU_PALETTE_ENTRY_BEGIN						(MAINMENU_HELP_BACKGROUND_PALETTE_ENTRY_BEGIN+MAINMENU_HELP_BACKGROUND_PALETTE_RESERVE_NUM)
#define MAINMENU_PALETTE_ENTRY_CONTENT_REGION				(MAINMENU_PALETTE_ENTRY_BEGIN)
#define MAINMENU_PALETTE_ENTRY_TITLE_STRING_1ST				(MAINMENU_PALETTE_ENTRY_BEGIN+1)	
#define MAINMENU_PALETTE_ENTRY_TITLE_STRING_2ND				(MAINMENU_PALETTE_ENTRY_BEGIN+2)	
#define MAINMENU_PALETTE_ENTRY_TITLE_STRING_3RD				(MAINMENU_PALETTE_ENTRY_BEGIN+3)	
#define MAINMENU_PALETTE_ENTRY_BUTTON_STRING                (MAINMENU_PALETTE_ENTRY_BEGIN+4)
#define MAINMENU_PALETTE_ENTRY_HELP_STRING                  (MAINMENU_PALETTE_ENTRY_BEGIN+5)
#define MAINMENU_PALETTE_ENTRY_BACKDOOR_STRING              (MAINMENU_PALETTE_ENTRY_BEGIN+6)


//define the palette color
#define MAINMENU_PALETTE_COLOR_BUTTON_STRING				0xFFFFFF
#define MAINMENU_PALETTE_COLOR_HELP_STRING                  0xFFFFFF    
#define MAINMENU_PALETTE_COLOR_BACKDOOR_STRING                          0x000000

#define MAINMENU_PALETTE_COLOR_CONTENT_REGION_1				0xAFCBE6 //0x8DB6DC
#define MAINMENU_PALETTE_COLOR_CONTENT_REGION_2				0xE0CCAD
#define MAINMENU_PALETTE_COLOR_CONTENT_REGION_3				0xFFF389 //0xFFD800
#define MAINMENU_PALETTE_COLOR_CONTENT_REGION_4				0xE5DB89

#define MAINMENU_PALETTE_COLOR_TITLE_STRING_1ST_1			0xFFFFFF
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_2ND_1			0xE8E680
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_3RD_1			0xA2C6E1

#define MAINMENU_PALETTE_COLOR_TITLE_STRING_1ST_2			0x901D1B
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_2ND_2			0x526D7D
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_3RD_2			0x3D5E35

#define MAINMENU_PALETTE_COLOR_TITLE_STRING_1ST_3			0x1C397C
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_2ND_3			0x206751 //0xD4633C
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_3RD_3			0xFFFFFF

#define MAINMENU_PALETTE_COLOR_TITLE_STRING_1ST_4			0x232743
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_2ND_4			0x6752A2
#define MAINMENU_PALETTE_COLOR_TITLE_STRING_3RD_4			0xFFFFFF


#ifdef SUPPORT_STB
extern BYTE __bMenuState;
extern BYTE __bMAINMENUDlgIndex;
#endif //SUPPORT_STB

//Export APIs
BYTE MAIN_MENU_ProcessKey(void);
void MAINMENU_Initial(void);
#ifdef SUPPORT_STB
BYTE MAINMENU_ProcessKey(BYTE bKey);
void MAINMENU_Trigger(void);
void MAINMENU_Recover(void);
#else
BYTE MAINMENU_Recover(BYTE bRecoverRegion);
#endif //SUPPORT_STB
void MAINMENU_DrawMainTitleBackground(BYTE bUIStyle);
void MAINMENU_DrawMainContentBackground(void);
void MAINMENU_DrawMainHelpBackground(BYTE bUIStyle);
void MAINMENU_DrawMainBackground(void);
void MAINMENU_ClearMainBackground(void);
void MAINMENU_ClearMainTitleBackground(BYTE bUIStyle, PARM_RECT *RectAttr);
#ifdef SUPPORT_STB
void MAINMENU_SubUIInitial(void);
void MAINMENU_DlgInitial(void);
void MAINMENU_Game_Menu_Initial(void);
void MAINMENU_Game_Menu_Recover(void);
void MAINMENU_Game_Menu_Exit(BYTE bClearBackground);
BYTE MAINMENU_Game_Menu_ProcessKey(BYTE bKey);
void MAINMENU_Game_Menu_Trigger(void);
void MAINMENU_Game_Menu_BackToPowerOnMenu(void);
void MAINMENU_JumpToState(BYTE bState);
void MAINMENU_DVD_Recover(BYTE bRecoverRegion);
#endif //SUPPORT_STB
void MAINMENU_DrawTitleString(WORD *pw1stTitle, WORD *pw2ndTitle, WORD *pw3rdTitle);
void MAINMENU_UseColorKey(PARM_DRAW_STRING *StringAttr);
void MAINMENU_DrawSelectionHelp(BYTE bUpDownOnly, BYTE bExitHelp);
void MAINMENU_LoadGroupPalette(BYTE bPaletteStartIndex, DWORD *dwPalette, BYTE bMixEnable);
void MAINMENU_InitializeGDI(BYTE bUIStyle);
void MAINMENU_DrawExitHelpOnly(void);
void MAINMENU_Exit(BYTE bClearBackground);
void MAINMENU_ExitAll(BYTE bClearBackground, BYTE bForceExit);

//Internal APIs
#ifdef SUPPORT_STB
void _MAINMENU_DrawButton(BYTE bButtonIndex, BYTE bType, BUTTON *pButton);
WORD _MAINMENU_GetMaxButtonStringWidth(BUTTON* pButton);
void _MAINMENU_DrawButtonString(BYTE bButtonIndex, BUTTON *pButton);
WORD _MAINMENU_GetButtonStartX(BUTTON *pButton);
WORD _MAINMENU_GetButtonStartY(BYTE bButtonIndex);
WORD _MAINMENU_GetButtonWidth(BUTTON *pButton);
void _MAINMENU_ProcessButton(void);
BYTE _MAINMENU_GetMenuFlowTableEntry(void);
BYTE _MAINMENU_GetNextMenuState(void);
void _MAINMENU_Game_Menu_DrawAllUI(void);
void _MAINMENU_Game_Menu_ProcessButton(void);
BYTE _MAINMENU_MoveCursorUp(void);
BYTE _MAINMENU_MoveCursorDown(void);
void _MAINMENU_UpdateButton(BYTE bNewCursor);
#endif //SUPPORT_STB
void _MAINMENU_DrawAllUI(void);
void _MAINMENU_InitDVDMode(void);
void _MAINMENU_ExitDVDMode(void);

#ifdef MAINMENU_MAIN_FILE
#ifdef SUPPORT_STB
#include "dvdsetup.h"
#include "dvbmenu.h"
#include "sysmenu.h"
//#include "setupstr.h"
#include "..\\..\\OSDString\\strextrn.h"

MENU_STATE _MenuStateTable[] = 
{
    {MS_DVD_SETUP, MS_MAIN_MENU},
    {MS_DVB_MENU, MS_MAIN_MENU},
    {MS_SYSTEM_SETTING, MS_MAIN_MENU},
    {MS_GAME, MS_MAIN_MENU},
    {MS_DVB_LANGUAGE, MS_DVB_MENU},
    {MS_DVB_TV_PROGRAM, MS_DVB_MENU},
	{MS_DVB_MUSIC_PROGRAM, MS_DVB_MENU},
	{MS_DVB_AUTO_SEARCH, MS_DVB_MENU},
	{MS_DVB_MANUAL_SEARCH, MS_DVB_MENU},
	{MS_DVB_PARENTAL_SETTING, MS_DVB_MENU},
	{MS_DVB_LANGUAGE, MS_DVB_MENU},
    {MS_DVB_TIME_SETTING, MS_DVB_MENU},
	{MS_DVB_SCHEDULE, MS_DVB_MENU},
    {MS_DVB_SCHEDULE_TIME_SETTING, MS_DVB_SCHEDULE},
#ifdef SUPPORT_219_OSDGAME //xuli.osdgame
#ifdef SUPPORT_GAME_MINER
    {MS_GAME_MINE, MS_GAME},//xuli.osdgame
#endif   
#ifdef SUPPORT_GAME_TETRIS
    {MS_GAME_TETRIS, MS_GAME},//xuli.osdgame
#endif
 #ifdef SUPPORT_GAME_GOMOKU
    {MS_GAME_GOMOKU, MS_GAME},//xuli.osdgame
#endif
 #ifdef SUPPORT_GAME_SOKOBAN
    {MS_GAME_SOKOBAN, MS_GAME},//xuli.osdgame
#endif
 #ifdef SUPPORT_GAME_RUSHHOUR
    {MS_GAME_RUSHHOUR, MS_GAME},//xuli.osdgame
#endif
#ifndef SUPPORT_POWERON_MENU
#ifdef SUPPORT_CALENDAR
    {MS_CALENDAR, MS_GAME},//xuli.osdgame
#endif //SUPPORT_CALENDAR
#endif //SUPPORT_POWERON_MENU
#endif //#ifdef SUPPORT_219_OSDGAME
};

MENU_FLOW _MenuFlowTable[] =
{    
    {MS_MAIN_MENU, MAINMENU_Initial, MAINMENU_ProcessKey, NULL, MAINMENU_Recover, NULL},
    {MS_DVD_SETUP, DVDSETUP_Initial, DVDSETUP_ProcessKey, NULL, DVDSETUP_Recover, DVDSETUP_Exit},
    {MS_DVB_MENU, DVBMENU_Main_Menu_Initial, DVBMENU_Main_Menu_ProcessKey, DVBMENU_Main_Menu_Trigger, DVBMENU_Main_Menu_Recover, DVBMENU_Main_Menu_Exit},
    {MS_SYSTEM_SETTING, SYSMENU_Initial, SYSMENU_ProcessKey, NULL, SYSMENU_Recover, SYSMENU_Exit},
    {MS_GAME, MAINMENU_Game_Menu_Initial, MAINMENU_Game_Menu_ProcessKey, NULL, MAINMENU_Game_Menu_Recover, MAINMENU_Game_Menu_Exit},    
    {MS_DVB_TV_PROGRAM, DVBMENU_TV_Porgram_Initial, DVBMENU_TV_Porgram_ProcessKey, NULL, NULL, DVBMENU_TV_Porgram_Exit},
    {MS_DVB_MUSIC_PROGRAM, DVBMENU_Music_Porgram_Initial, DVBMENU_Music_Program_ProcessKey, NULL, NULL, DVBMENU_Music_Porgram_Exit},
    {MS_DVB_AUTO_SEARCH, DVBMENU_Auto_Search_Initial, DVBMENU_Auto_Search_ProcessKey, DVBMENU_Auto_Search_Trigger, NULL, DVBMENU_Auto_Search_Exit},
    {MS_DVB_MANUAL_SEARCH, DVBMENU_Manual_Search_Initial, DVBMENU_Manual_Search_ProcessKey, DVBMENU_Manual_Search_Trigger, NULL, DVBMENU_Manual_Search_Exit},
    {MS_DVB_PARENTAL_SETTING, DVBMENU_Parental_Setting_Initial, DVBMENU_Parental_Setting_ProcessKey, NULL, NULL, DVBMENU_Parental_Setting_Exit},
    {MS_DVB_LANGUAGE, DVBMENU_Language_Initial, DVBMENU_Language_ProcessKey, NULL, NULL, DVBMENU_Language_Exit},
    {MS_DVB_TIME_SETTING, DVBMENU_Time_Setting_Initial, DVBMENU_Time_Setting_ProcessKey, NULL, NULL, DVBMENU_Time_Setting_Exit},
    {MS_DVB_SCHEDULE, DVBMENU_Schedule_Initial, DVBMENU_Schedule_ProcessKey, NULL, DVBMENU_Schedule_Recover, DVBMENU_Schedule_Exit},
    {MS_DVB_SCHEDULE_TIME_SETTING, DVBMENU_Schedule_Time_Setting_Initial, DVBMENU_Schedule_Time_Setting_ProcessKey, NULL, NULL, DVBMENU_Schedule_Time_Setting_Exit},
#ifdef SUPPORT_GAME_MINER
    {MS_GAME_MINE, GAME_MINE_Initial, GAME_MINE_ProcessKey, GAME_MINE_Trigger, NULL, GAME_MINE_Exit}, 
#endif
#ifdef SUPPORT_GAME_TETRIS
    {MS_GAME_TETRIS, GAME_TETRIS_Initial, GAME_TETRIS_ProcessKey, GAME_TETRIS_Trigger, NULL, GAME_TETRIS_Exit},
#endif
#ifdef SUPPORT_GAME_GOMOKU
    {MS_GAME_GOMOKU, GAME_GOMOKU_Initial, GAME_GOMOKU_ProcessKey, NULL, NULL, GAME_GOMOKU_Exit},
#endif
#ifdef SUPPORT_GAME_SOKOBAN
    {MS_GAME_SOKOBAN, GAME_SOKOBAN_Initial, GAME_SOKOBAN_ProcessKey, GAME_SOKOBAN_Trigger, NULL, GAME_SOKOBAN_Exit},
#endif
#ifdef SUPPORT_GAME_RUSHHOUR
    {MS_GAME_RUSHHOUR, GAME_RUSHHOUR_Initial, GAME_RUSHHOUR_ProcessKey, NULL, NULL, GAME_RUSHHOUR_Exit},
#endif
#ifndef SUPPORT_POWERON_MENU
#ifdef SUPPORT_CALENDAR
   {MS_CALENDAR, CALENDAR_Initial, CALENDAR_ProcessKey, NULL,NULL,CALENDAR_Exit}    
#endif //SUPPORT_CALENDAR    
#endif //SUPPORT_POWERON_MENU
};
#endif //SUPPORT_STB 

BYTE _bMAINMENUTitlePalette1[MAINMENU_TITLE_REGION_HEIGHT] =
{
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_13
};

BYTE _bMAINMENUTitlePalette2[MAINMENU_TITLE_REGION_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_14, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_14, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_14, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_14
};

BYTE _bMAINMENUTitlePalette3[MAINMENU_TITLE_REGION_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9
};

BYTE _bMAINMENUTitlePalette4[MAINMENU_TITLE_REGION_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_TITLE_REGION_PALETTE_0,
};


BYTE _bMAINMENUHelpPalette1[MAINMENU_HELP_REGION_HEIGHT] =
{
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12
};

BYTE _bMAINMENUHelpPalette2[MAINMENU_HELP_REGION_HEIGHT] =
{
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_13, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_14, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_14, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_14
};

BYTE _bMAINMENUHelpPalette3[MAINMENU_HELP_REGION_HEIGHT] =
{
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11
};

BYTE _bMAINMENUHelpPalette4[MAINMENU_HELP_REGION_HEIGHT] =
{
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_2, 
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0, MAINMENU_PALETTE_ENTRY_HELP_REGION_PALETTE_0
};

#ifdef SUPPORT_STB
BUTTON _bMAINMENUButton[MAINMENU_BUTTON_NUM] = {
#ifdef SUPPORT_DMP
    {MAINMENU_BUTTON_DVD_SETUP, aMENUButtonPlaySetup},
#else
    {MAINMENU_BUTTON_DVD_SETUP, aMENUButtonDVDSetup},
#endif //SUPPORT_DMP
    {MAINMENU_BUTTON_DVB_MENU, aMENUButtonDVBMenu},
    {MAINMENU_BUTTON_SYSTEM_SETTING, aMENUButtonSystemSetting},
#ifndef SUPPORT_POWERON_MENU
    {MAINMENU_BUTTON_GAME, aMENUButtonGame},
#endif //SUPPORT_POWERON_MENU
    {MAINMENU_BUTTON_EXIT, aMENUButtonExit},
};

BUTTON _bMAINMENUGameButton[MAINMENU_GAME_BUTTON_NUM] = {
#ifdef SUPPORT_GAME_MINER
    {MAINMENU_GAME_BUTTON_MINE, aMENUButtonGameMine},
#endif
#ifdef SUPPORT_GAME_TETRIS
    {MAINMENU_GAME_BUTTON_TETRIS, aMENUButtonGameTetris},
#endif
#ifdef SUPPORT_GAME_GOMOKU
    {MAINMENU_GAME_BUTTON_GOMOKU, aMENUButtonGameGomoku},
#endif
#ifdef SUPPORT_GAME_SOKOBAN
    {MAINMENU_GAME_BUTTON_SOKOBAN, aMENUSButtonGameSokoban},   //xuli.osdgame
#endif
#ifdef SUPPORT_GAME_RUSHHOUR
    {MAINMENU_GAME_BUTTON_RUSHHOUR, aMENUButtonGameRushHour},    //xuli.osdgame
#endif
#ifndef SUPPORT_POWERON_MENU
#ifdef SUPPORT_CALENDAR
    {MAINMENU_GAME_BUTTON_CALENDAR, aMENUButtonGameCalendar},
#endif  
#endif //SUPPORT_POWERON_MENU    
    {MAINMENU_GAME_BUTTON_EXIT, aMENUButtonExit},
};
    
BYTE _bMAINMENUButtonNormalPalette1[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_14,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_14,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0
};

BYTE _bMAINMENUButtonNormalPalette2[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6, 
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0
};

/*
BYTE _bMAINMENUButtonNormalPalette3[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0
};
*/
BYTE _bMAINMENUButtonNormalPalette3[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_12, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_12,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_11,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_10,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
    MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0
};


BYTE _bMAINMENUButtonNormalPalette4[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_NORMAL_BUTTON_PALETTE_0
};

BYTE _bMAINMENUButtonHighlightPalette1[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_14,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_14,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_13,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_12,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0
};

BYTE _bMAINMENUButtonHighlightPalette2[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_11,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_10,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_9,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0,
};

BYTE _bMAINMENUButtonHighlightPalette3[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0
};

BYTE _bMAINMENUButtonHighlightPalette4[MAINMENU_BUTTON_HEIGHT] = 
{
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_8,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_7,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_6,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_5,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_4,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_3,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2, MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_2,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_1,
	MAINMENU_PALETTE_ENTRY_HIGHLIGHT_BUTTON_PALETTE_0
};

BYTE _bMAINMENUButtonDisablePalette[MAINMENU_BUTTON_HEIGHT] = 
{
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_0,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_1,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_2,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_3,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_4,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_5,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_6,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_7,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_8,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_9,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_10,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_11, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_12, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_13, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_14, MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_14,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_13, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_12, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_11, 
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_10,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_9,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_8,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_7,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_6,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_5,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_4,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_3,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_2,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_1,
    MAINMENU_PALETTE_ENTRY_DISABLE_BUTTON_PALETTE_0,
};
	
DLG_FLOW _DlgFlowTable[] = 
{
    {PIN_Initial, PIN_ProcessKey, NULL, NULL, PIN_Exit, NULL, MS_DVB_MENU, MAINMENU_INVALID_MENU_STATE, MAINMENU_INVALID_DLG_SATE},
    {PIN_Initial, PIN_ProcessKey, NULL, NULL, PIN_Exit, NULL, MS_DVB_MENU, MS_DVB_PARENTAL_SETTING, MAINMENU_INVALID_DLG_SATE},
#ifndef IMAGE_FRAME_SETUP
    {PIN_Initial, PIN_ProcessKey, NULL, NULL, PIN_Exit, DVDSETUP_ParentalCtl_Callback, MS_DVD_SETUP, MAINMENU_INVALID_MENU_STATE, MAINMENU_INVALID_DLG_SATE},
    {LanguageCode_Initial, LanguageCode_ProcessKey, NULL, NULL, LanguageCode_Exit, LanguageCode_Callback, MS_DVD_SETUP, MAINMENU_INVALID_MENU_STATE, MAINMENU_INVALID_DLG_SATE},
#endif //IMAGE_FRAME_SETUP
    {PINDLG_CHANGE_PIN_Initial, PINDLG_CHANGE_PIN_ProcessKey, NULL, PINDLG_CHANGE_PIN_Recover, PINDLG_CHANGE_PIN_Exit, NULL, MS_SYSTEM_SETTING, MAINMENU_INVALID_MENU_STATE, MAINMENU_INVALID_DLG_SATE},
};

#endif //#ifdef SUPPORT_STB

DWORD _dwMAINMENUTitleRegionPalette1[] =
{
    14,
	0x2E7237,
	0x33753C,
	0x3B7A44,
	0x45814D,
	0x508858,
	0x5C8F63,
	0x66956C,
	0x6F9B74,
	0x76A07C,
	0x7CA381,
	0xC1D4C4,
	0xFEFEFE,
	0xE3EDF7,
	0xB9D2E9,
};

DWORD _dwMAINMENUTitleRegionPalette2[] =
{
    15,
	0xC07422,
	0xC37927,
	0xC67F2E,
	0xCB8838,
	0xD09243,
	0xD59B4D,
	0xDAA557,
	0xDFAE62,
	0xE4B86D,
	0xEBC57A,
	0xF1D087,
	0xF5D990,
	0xF8DD95,
	0xF9E098,
	0xFAE29A,
};

DWORD _dwMAINMENUTitleRegionPalette3[] =
{
    10,
	0x20A5D6,
	0x2AA9D7,
	0x35ADD8,
	0x42B1DA,
	0x51B7DC,
	0x63BDDD,
	0x77C4E0,
	0x8ACBE2,
	0x9AD0E4,
	0xA6D4E5,
};

DWORD _dwMAINMENUTitleRegionPalette4[] =
{
    11,
	0x6487B9,
	0x6689BB,
	0x6C8DBD,
	0x7191BF,
	0x7796C2,
	0x7D9AC4,
	0x849FC7,
	0x8BA5CB,
	0x92ABCE,
	0x97AED0,
	0x99B0D1,
};

DWORD _dwMAINMENUHelpRegionPalette1[] =
{
    13,
	0xB9D2E9,
	0xE3EDF7,
	0xD8E6F3,
	0x837DA8,
	0x7C76A4,
	0x746DA1,
	0x6C649C,
	0x645C98,
	0x5C5395,
	0x544B91,
	0x4D438E,
	0x473D8B,
	0x423789,
};

DWORD _dwMAINMENUHelpRegionPalette2[] =
{
    15,
	0xFAE29A,
	0xF9E098,
	0xF8DD95,
	0xF5D990,
	0xF1D087,
	0xEBC57A,
	0xE4B86D,
	0xDFAE62,
	0xDAA557,
	0xD59B4D,
	0xD09243,
	0xCB8838,
	0xC67F2E,
	0xC37927,
	0xC07422
};

DWORD _dwMAINMENUHelpRegionPalette3[] =
{
    12,
	0xDDBAAE,
	0xDCB6A9,
	0xDCB1A3,
	0xDCAC9C,
	0xDBA794,
	0xDB9F8A,
	0xD9957D,
	0xD88A6F,
	0xD78062,
	0xD67756,
	0xD66D49,
	0xD4633C
};

DWORD _dwMAINMENUHelpRegionPalette4[] =
{
    12,
	0x8E79C8,
	0x917DCA,
	0x9582CB,
	0x9A87CE,
	0x9E8CD0,
	0xA190D2,
	0xA595D4,
	0xAA9AD6,
	0xAD9ED7,
	0xAFA1D8,
	0xB2A4DA,
	0xB5A8DB,
};

DWORD _dwMAINMENUNormalButtonPalette1[] = 
{
    15,
	0x5F9479,
	0x31743A,
	0x34763C,
	0x387940,
	0x3C7B44,
	0x43804B,
	0x4A8452,
	0x558B5C,
	0x5E9164,
	0x69996F,
	0x76A17C,
	0x7EA783,
	0x89AF8E,
	0x91B596,
	0x97B89B,
};

DWORD _dwMAINMENUNormalButtonPalette2[] =
{
    9,
	0x889494,
	0x698595,
	0x6D8898,
	0x728C9C,
	0x7A93A2,
	0x839BA8,
	0x8EA3AF,
	0x97ABB6,
	0xA1B2BD,
};

DWORD _dwMAINMENUNormalButtonPalette3[] =
{
    13,
    0x64A188,
    0x258ABF,
    0x2A8DC0,
    0x308FC1,
    0x3693C3,
    0x3F98C6,
    0x479CC8,
    0x51A2CB,
    0x5BA7CE,
    0x64ABD1,
    0x6DB0D3,
    0x74B4D5,
    0x78B6D7,
};

DWORD _dwMAINMENUNormalButtonPalette4[] =
{
    8,
	0xADA3A5,
	0x958CB4,
	0x9B92B8,
	0xA39ABD,
	0xACA4C4,
	0xB3ACC9,
	0xB9B3CD,
	0xBDB7D0,
};

DWORD _dwMAINMENUHighlightButtonPalette1[] =
{
    15,
	0x9F8672,
	0xA87648,
	0xAA7A4E,
	0xAD7D53,
	0xB1845B,
	0xB58A63,
	0xBA926E,
	0xBE9A78,
	0xC4A384,
	0xCAAC91,
	0xD0B49B,
	0xD4BBA4,
	0xD8C0AC,
	0xDAC4B0,
	0xDBC5B2,
};

DWORD _dwMAINMENUHighlightButtonPalette2[] =
{
    12,
	0xBE925F,
	0xB5814A,
	0xB6844E,
	0xB78651,
	0xB98955,
	0xBB8D5A,
	0xBE9262,
	0xC2996C,
	0xC8A279,
	0xCCAA83,
	0xD0B08D,
	0xD1B291,
};

DWORD _dwMAINMENUHighlightButtonPalette3[] =
{
    9,
	0xE0A32B,
	0xD59041,
	0xD69549,
	0xD8984F,
	0xD99D57,
	0xDBA15E,
	0xDEA86B,
	0xE2B27B,
	0xE5B988,
};

DWORD _dwMAINMENUHighlightButtonPalette4[] =
{
    9,
	0xD6A342,
	0xCF871F,
	0xD18A24,
	0xD28E2C,
	0xD59639,
	0xD89C46,
	0xDBA555,
	0xDEAB63,
	0xE1B473,
};

DWORD _dwMAINMENUDisableButtonPalette[] =
{
    15,
    0xA8B4BF,
    0xB4B4B3,
    0xB6B6B5,
    0xB7B7B6,
    0xBABAB9,
    0xBCBCBB,
    0xC0C0BF,
    0xC4C4C3,
    0xC8C8C7,
    0xCCCCCB,
    0xD0D0CF,
    0xD4D4D3,
    0xD7D7D6,
    0xD8D8D8,
    0xD9D9D8,
};
    


#endif //MAINMENU_MAIN_FILE


#endif //__MAIN_MENU_H__
